# Data Description 


Estimating churners prior to their abandonment of a product or service is crucial. In this machine learning assignment, I will design a churn prediction model for the telecom industry to forecast which customers are most likely to churn.

The 39 features of this dataset are as follows:

1. Acronyms: Descriptions
2. MOBILE_NUMBER: Customer phone number
3. CIRCLE_ID: Telecom circle area to which the customer belongs to
4. LOC	Local calls: within same telecom circle
5. STD	STD calls: outside the calling circle
6. IC: Incoming calls
7. OG: Outgoing calls
8. T2T: Operator T to T, i.e. within same operator (mobile to mobile)
9. T2M: Operator T to other operator mobile
10. T2O: Operator T to other operator fixed line
11. T2F: Operator T to fixed lines of T
12. T2C: Operator T to it’s own call center
13. ARPU: Average revenue per user
14. MOU: Minutes of usage - voice calls
15. AON: Age on network - number of days the customer is using the operator T network
16. ONNET: All kind of calls within the same operator network
17. OFFNET:    	All kind of calls outside the operator T network
18. ROAM:	Indicates that customer is in roaming zone during the call
19. SPL:   	Special calls
20. ISD:    	ISD calls
21. RECH:    	Recharge
22. NUM:    	Number
23. AMT:    	Amount in local currency
24. MAX:    	Maximum
25. DATA:    	Mobile internet
26. 3G:    	3G network
27. AV:    	Average
28. VOL:    	Mobile internet usage volume (in MB)
29. 2G:    	2G network
30. PCK:    	Prepaid service schemes called - PACKS
31. NIGHT:    	Scheme to use during specific night hours only
32. MONTHLY:    	Service schemes with validity equivalent to a month
33. SACHET:   	Service schemes with validity smaller than a month
34. *.6:    	KPI for the month of June
35. *.7:    	KPI for the month of July
36. *.8:    	KPI for the month of August
37. *.9:    	KPI for the month of September
38. FB_USER:	Service scheme to avail services of Facebook and similar social networking sites
39. VBC:    	Volume based cost - when no specific scheme is not purchased and paid as per usage

# Problem Statement

In the telecommunications business, clients may pick from a variety of service providers and actively switch from one to another. In this extremely competitive sector, the yearly turnover rate for the telecoms industry averages between 15 and 25 percent. Given that it costs five to ten times as much to gain a new client as it does to maintain an existing one, customer retention is now more crucial than customer acquisition.

Retaining high-profitable clients is the primary business objective for many incumbent operators of T. To decrease customer turnover, telecom businesses must anticipate which consumers are at high risk of churning.

# Aim

In this project, I am going to analyze the customer-level data of a large telecommunications company, develop predictive models to identify consumers at high risk of churn, and identify the primary signs of churn.

# Tech stack

* Language – Python
* Libraries - Numpy, Pandas, Matplotlib, Seaborn, Scikit-learn,

# Approach

1. Importing the required libraries and reading the dataset.
    * Understanding the dataset
2. Exploratory Data Analysis (EDA) –
3. Filtering High Value Customers
4. Creating target Variable
5. Developing new features
6. Handling Missing values
7. Data Visualization-Univariate Analysis
8. Data Visualization- Bivariate Analysis
9. Outlier Detection
10. Data Preparation
11. Data Modeling and Eavlaution
12. Non-Interpretable Models
13. Interpretable Models
14. Conclusion

# 1. Understanding the dataset

In [1]:
%%HTML
<style type="text/css">
table.dataframe td, table.dataframe th {
    border: 1px  black solid !important;
  color: black !important;
}
</style>

## 1.1 Importing Libraries

In [2]:
!pip install graphviz

Requirement already satisfied: graphviz in /opt/homebrew/Caskroom/miniforge/base/envs/tensorflow/lib/python3.9/site-packages (0.20.1)

In [3]:
#Importing Data Reading and Processing Libraries
import pandas as pd
import numpy as np

#Imporitng Data Visualization Libraries
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

#Importing Data Preparation and Modeling Libraries
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold, GridSearchCV,StratifiedKFold

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier


#Importing Warning Libraries
import warnings
warnings.filterwarnings("ignore")

#Importing Miscellaneous Libraries
pd.set_option("display.max_columns",None)
pd.set_option("display.max_rows",None)
pd.set_option('display.width', None)

# Import the StandardScaler()
from sklearn.preprocessing import StandardScaler

#Improting the PCA module
from sklearn.decomposition import PCA

# For Hopkins test
from sklearn.neighbors import NearestNeighbors
from random import sample
from numpy.random import uniform
import numpy as np
from math import isnan

# For clustering 
## using KMeans ##
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# Importing classification report and confusion matrix from sklearn metrics
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.metrics import recall_score,roc_auc_score,roc_curve

## using Hierarchical ##
from scipy.cluster.hierarchy import linkage
from scipy.cluster.hierarchy import dendrogram
from scipy.cluster.hierarchy import cut_tree

# Importing required packages for visualization
from IPython.display import Image  
#from sklearn.externals.six import StringIO  
from sklearn.tree import export_graphviz
import pydot, graphviz


# Other sklearn packages
import sklearn.metrics as metrics
from xgboost import XGBClassifier
from sklearn.tree import DecisionTreeClassifier

from datetime import date,datetime
import math
import multiprocessing

print("Successfully Importing Libraries...")

Successfully Importing Libraries...

# 1.2 Dataset Loading

In [4]:
df = pd.read_csv('telecom_churn_data.csv')
print("Successully Datset Load..")
df.sample(2)

Successully Datset Load..

,mobile_number,circle_id,loc_og_t2o_mou,std_og_t2o_mou,loc_ic_t2o_mou,last_date_of_month_6,last_date_of_month_7,last_date_of_month_8,last_date_of_month_9,arpu_6,arpu_7,arpu_8,arpu_9,onnet_mou_6,onnet_mou_7,onnet_mou_8,onnet_mou_9,offnet_mou_6,offnet_mou_7,offnet_mou_8,offnet_mou_9,roam_ic_mou_6,roam_ic_mou_7,roam_ic_mou_8,roam_ic_mou_9,roam_og_mou_6,roam_og_mou_7,roam_og_mou_8,roam_og_mou_9,loc_og_t2t_mou_6,loc_og_t2t_mou_7,loc_og_t2t_mou_8,loc_og_t2t_mou_9,loc_og_t2m_mou_6,loc_og_t2m_mou_7,loc_og_t2m_mou_8,loc_og_t2m_mou_9,loc_og_t2f_mou_6,loc_og_t2f_mou_7,loc_og_t2f_mou_8,loc_og_t2f_mou_9,loc_og_t2c_mou_6,loc_og_t2c_mou_7,loc_og_t2c_mou_8,loc_og_t2c_mou_9,loc_og_mou_6,loc_og_mou_7,loc_og_mou_8,loc_og_mou_9,std_og_t2t_mou_6,std_og_t2t_mou_7,std_og_t2t_mou_8,std_og_t2t_mou_9,std_og_t2m_mou_6,std_og_t2m_mou_7,std_og_t2m_mou_8,std_og_t2m_mou_9,std_og_t2f_mou_6,std_og_t2f_mou_7,std_og_t2f_mou_8,std_og_t2f_mou_9,std_og_t2c_mou_6,std_og_t2c_mou_7,std_og_t2c_mou_8,std_og_t2c_mou_9,std_og_mou_6,std_og_mou_7,std_og_mou_8,std_og_mou_9,isd_og_mou_6,isd_og_mou_7,isd_og_mou_8,isd_og_mou_9,spl_og_mou_6,spl_og_mou_7,spl_og_mou_8,spl_og_mou_9,og_others_6,og_others_7,og_others_8,og_others_9,total_og_mou_6,total_og_mou_7,total_og_mou_8,total_og_mou_9,loc_ic_t2t_mou_6,loc_ic_t2t_mou_7,loc_ic_t2t_mou_8,loc_ic_t2t_mou_9,loc_ic_t2m_mou_6,loc_ic_t2m_mou_7,loc_ic_t2m_mou_8,loc_ic_t2m_mou_9,loc_ic_t2f_mou_6,loc_ic_t2f_mou_7,loc_ic_t2f_mou_8,loc_ic_t2f_mou_9,loc_ic_mou_6,loc_ic_mou_7,loc_ic_mou_8,loc_ic_mou_9,std_ic_t2t_mou_6,std_ic_t2t_mou_7,std_ic_t2t_mou_8,std_ic_t2t_mou_9,std_ic_t2m_mou_6,std_ic_t2m_mou_7,std_ic_t2m_mou_8,std_ic_t2m_mou_9,std_ic_t2f_mou_6,std_ic_t2f_mou_7,std_ic_t2f_mou_8,std_ic_t2f_mou_9,std_ic_t2o_mou_6,std_ic_t2o_mou_7,std_ic_t2o_mou_8,std_ic_t2o_mou_9,std_ic_mou_6,std_ic_mou_7,std_ic_mou_8,std_ic_mou_9,total_ic_mou_6,total_ic_mou_7,total_ic_mou_8,total_ic_mou_9,spl_ic_mou_6,spl_ic_mou_7,spl_ic_mou_8,spl_ic_mou_9,isd_ic_mou_6,isd_ic_mou_7,isd_ic_mou_8,isd_ic_mou_9,ic_others_6,ic_others_7,ic_others_8,ic_others_9,total_rech_num_6,total_rech_num_7,total_rech_num_8,total_rech_num_9,total_rech_amt_6,total_rech_amt_7,total_rech_amt_8,total_rech_amt_9,max_rech_amt_6,max_rech_amt_7,max_rech_amt_8,max_rech_amt_9,date_of_last_rech_6,date_of_last_rech_7,date_of_last_rech_8,date_of_last_rech_9,last_day_rch_amt_6,last_day_rch_amt_7,last_day_rch_amt_8,last_day_rch_amt_9,date_of_last_rech_data_6,date_of_last_rech_data_7,date_of_last_rech_data_8,date_of_last_rech_data_9,total_rech_data_6,total_rech_data_7,total_rech_data_8,total_rech_data_9,max_rech_data_6,max_rech_data_7,max_rech_data_8,max_rech_data_9,count_rech_2g_6,count_rech_2g_7,count_rech_2g_8,count_rech_2g_9,count_rech_3g_6,count_rech_3g_7,count_rech_3g_8,count_rech_3g_9,av_rech_amt_data_6,av_rech_amt_data_7,av_rech_amt_data_8,av_rech_amt_data_9,vol_2g_mb_6,vol_2g_mb_7,vol_2g_mb_8,vol_2g_mb_9,vol_3g_mb_6,vol_3g_mb_7,vol_3g_mb_8,vol_3g_mb_9,arpu_3g_6,arpu_3g_7,arpu_3g_8,arpu_3g_9,arpu_2g_6,arpu_2g_7,arpu_2g_8,arpu_2g_9,night_pck_user_6,night_pck_user_7,night_pck_user_8,night_pck_user_9,monthly_2g_6,monthly_2g_7,monthly_2g_8,monthly_2g_9,sachet_2g_6,sachet_2g_7,sachet_2g_8,sachet_2g_9,monthly_3g_6,monthly_3g_7,monthly_3g_8,monthly_3g_9,sachet_3g_6,sachet_3g_7,sachet_3g_8,sachet_3g_9,fb_user_6,fb_user_7,fb_user_8,fb_user_9,aon,aug_vbc_3g,jul_vbc_3g,jun_vbc_3g,sep_vbc_3g
26249,7000125802,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,196.446,14.54,304.631,73.547,0.00,0.00,56.73,0.00,10.04,10.09,119.41,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,2.56,0.00,0.00,1.23,7.11,0.00,0.0,0.00,0.00,0.0,2.06,0.0,0.00,0.0,0.00,1.23,9.68,0.00,0.00,0.00,54.16,0.00,0.00,7.06,93.59,0.00,0.0,1.8,0.0,0.0,0.0,0.0,0.0,0.0,0.00,8.86,147.76,0.00,0.0,0.0,0.0,0.0,10.91,1.43,18.69,0.00,0.00,0.0,0.0,0.0,10.91,11.53,176.14,0.00,3.41,0.50,0.00,0.83,0.00,0.63,8.48,3.24,0.0,0.00,3.58,0.00,3.41,1.13,12.06,4.08,0.00,0.00,2.21,0.00,0.25,0.00,2.66,0.00,0.0,0.31,0.63,1.93,0.0,0.0,0.0,0.0,0.25,0.31,5.51,1.93,3.66,1.44,18.04,6.01,0.0,0.0,0.0,0.0,0.0,0.0,0.46,0.0,0.00,0.0,0.0,0.0,6,4,12,8,233,30,347,89,154,30,50,25,6/12/2014,7/29/2014,8/31/2014,9/29/2014,0,30,14,0,6/10/2014,NaN,8/31/2014,9/13/2014,4.0,NaN,6.0,4.0,154.0,NaN,46.0,25.0,1.0,NaN,6.0,4.0,3.0,NaN,0.0,0.0,223.0,NaN,181.0,89.0,1331.76,0.0,154.28,0.54,0.0,0.0,718.29,303.28,58.89,NaN,34.61,0.0,66.79,NaN,0.0,0.0,0.0,NaN,0.0,0.0,1,0,0,0,0,0,6,4,0,0,0,0,3,0,0,0,1.0,NaN,1.0,1.0,418,215.75,0.0,0.0,0.0
35840,7000140523,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,9/30/2014,1690.836,2064.99,1850.739,2052.249,450.53,1518.56,1457.88,2682.61,1990.31,2038.28,1794.41,1204.14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,148.31,1074.36,548.34,217.08,1125.04,1657.83,1129.91,321.38,0.0,0.25,0.13,0.0,0.00,0.0,2.66,0.0,1273.36,2732.44,1678.39,538.46,302.21,444.19,909.53,2465.53,865.09,380.19,660.23,882.76,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1167.31,824.39,1569.76,3348.29,0.0,0.0,0.0,0.0,0.16,7.58,8.16,27.11,4.76,0.0,0.0,0.0,2445.61,3564.43,3256.33,3913.88,131.23,594.58,35.64,151.31,1179.74,202.51,251.48,254.58,0.0,12.88,20.71,0.85,1310.98,809.98,307.84,406.74,65.58,46.54,1462.71,839.81,66.98,238.68,360.96,456.91,0.0,0.25,0.00,0.21,0.0,0.0,0.0,0.0,132.56,285.48,1823.68,1296.94,1444.03,1095.46,2131.53,1703.69,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.48,0.0,0.0,0.0,64,73,56,54,1989,2396,2155,2338,110,110,144,150,6/30/2014,7/31/2014,8/31/2014,9/28/2014,20,50,50,150,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.00,0.00,0.0,0.0,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,1449,0.00,0.0,0.0,0.0

In [5]:
df.shape

(99999, 226)

`Observation`: Number of rows: 99999, 
               Number of columns: 226

In [6]:
df.info(verbose=1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99999 entries, 0 to 99998
Data columns (total 226 columns):
 #    Column                    Dtype
---   ------                    -----
 0    mobile_number             int64
 1    circle_id                 int64
 2    loc_og_t2o_mou            float64
 3    std_og_t2o_mou            float64
 4    loc_ic_t2o_mou            float64
 5    last_date_of_month_6      object
 6    last_date_of_month_7      object
 7    last_date_of_month_8      object
 8    last_date_of_month_9      object
 9    arpu_6                    float64
 10   arpu_7                    float64
 11   arpu_8                    float64
 12   arpu_9                    float64
 13   onnet_mou_6               float64
 14   onnet_mou_7               float64
 15   onnet_mou_8               float64
 16   onnet_mou_9               float64
 17   offnet_mou_6              float64
 18   offnet_mou_7              float64
 19   offnet_mou_8              float64
 20   offnet_mou_9              float64
 21   roam_ic_mou_6             float64
 22   roam_ic_mou_7             float64
 23   roam_ic_mou_8             float64
 24   roam_ic_mou_9             float64
 25   roam_og_mou_6             float64
 26   roam_og_mou_7             float64
 27   roam_og_mou_8             float64
 28   roam_og_mou_9             float64
 29   loc_og_t2t_mou_6          float64
 30   loc_og_t2t_mou_7          float64
 31   loc_og_t2t_mou_8          float64
 32   loc_og_t2t_mou_9          float64
 33   loc_og_t2m_mou_6          float64
 34   loc_og_t2m_mou_7          float64
 35   loc_og_t2m_mou_8          float64
 36   loc_og_t2m_mou_9          float64
 37   loc_og_t2f_mou_6          float64
 38   loc_og_t2f_mou_7          float64
 39   loc_og_t2f_mou_8          float64
 40   loc_og_t2f_mou_9          float64
 41   loc_og_t2c_mou_6          float64
 42   loc_og_t2c_mou_7          float64
 43   loc_og_t2c_mou_8          float64
 44   loc_og_t2c_mou_9          float64
 45   loc_og_mou_6              float64
 46   loc_og_mou_7              float64
 47   loc_og_mou_8              float64
 48   loc_og_mou_9              float64
 49   std_og_t2t_mou_6          float64
 50   std_og_t2t_mou_7          float64
 51   std_og_t2t_mou_8          float64
 52   std_og_t2t_mou_9          float64
 53   std_og_t2m_mou_6          float64
 54   std_og_t2m_mou_7          float64
 55   std_og_t2m_mou_8          float64
 56   std_og_t2m_mou_9          float64
 57   std_og_t2f_mou_6          float64
 58   std_og_t2f_mou_7          float64
 59   std_og_t2f_mou_8          float64
 60   std_og_t2f_mou_9          float64
 61   std_og_t2c_mou_6          float64
 62   std_og_t2c_mou_7          float64
 63   std_og_t2c_mou_8          float64
 64   std_og_t2c_mou_9          float64
 65   std_og_mou_6              float64
 66   std_og_mou_7              float64
 67   std_og_mou_8              float64
 68   std_og_mou_9              float64
 69   isd_og_mou_6              float64
 70   isd_og_mou_7              float64
 71   isd_og_mou_8              float64
 72   isd_og_mou_9              float64
 73   spl_og_mou_6              float64
 74   spl_og_mou_7              float64
 75   spl_og_mou_8              float64
 76   spl_og_mou_9              float64
 77   og_others_6               float64
 78   og_others_7               float64
 79   og_others_8               float64
 80   og_others_9               float64
 81   total_og_mou_6            float64
 82   total_og_mou_7            float64
 83   total_og_mou_8            float64
 84   total_og_mou_9            float64
 85   loc_ic_t2t_mou_6          float64
 86   loc_ic_t2t_mou_7          float64
 87   loc_ic_t2t_mou_8          float64
 88   loc_ic_t2t_mou_9          float64
 89   loc_ic_t2m_mou_6          float64
 90   loc_ic_t2m_mou_7          float64
 91   loc_ic_t2m_mou_8          float64
 92   loc_ic_t2m_mou_9          float64
 93   loc_ic_t2f_mou_6          float64
 94   loc_ic_t2f_mou_7          float64
 95   loc_ic_t2f_mou_8          float64
 96   loc_ic_t2f_mou_9          float64
 97   loc_ic_mou_6              float64
 98   loc_ic_mou_7              float64
 99   loc_ic_mou_8              float64
 100  loc_ic_mou_9              float64
 101  std_ic_t2t_mou_6          float64
 102  std_ic_t2t_mou_7          float64
 103  std_ic_t2t_mou_8          float64
 104  std_ic_t2t_mou_9          float64
 105  std_ic_t2m_mou_6          float64
 106  std_ic_t2m_mou_7          float64
 107  std_ic_t2m_mou_8          float64
 108  std_ic_t2m_mou_9          float64
 109  std_ic_t2f_mou_6          float64
 110  std_ic_t2f_mou_7          float64
 111  std_ic_t2f_mou_8          float64
 112  std_ic_t2f_mou_9          float64
 113  std_ic_t2o_mou_6          float64
 114  std_ic_t2o_mou_7          float64
 115  std_ic_t2o_mou_8          float64
 116  std_ic_t2o_mou_9          float64
 117  std_ic_mou_6              float64
 118  std_ic_mou_7              float64
 119  std_ic_mou_8              float64
 120  std_ic_mou_9              float64
 121  total_ic_mou_6            float64
 122  total_ic_mou_7            float64
 123  total_ic_mou_8            float64
 124  total_ic_mou_9            float64
 125  spl_ic_mou_6              float64
 126  spl_ic_mou_7              float64
 127  spl_ic_mou_8              float64
 128  spl_ic_mou_9              float64
 129  isd_ic_mou_6              float64
 130  isd_ic_mou_7              float64
 131  isd_ic_mou_8              float64
 132  isd_ic_mou_9              float64
 133  ic_others_6               float64
 134  ic_others_7               float64
 135  ic_others_8               float64
 136  ic_others_9               float64
 137  total_rech_num_6          int64
 138  total_rech_num_7          int64
 139  total_rech_num_8          int64
 140  total_rech_num_9          int64
 141  total_rech_amt_6          int64
 142  total_rech_amt_7          int64
 143  total_rech_amt_8          int64
 144  total_rech_amt_9          int64
 145  max_rech_amt_6            int64
 146  max_rech_amt_7            int64
 147  max_rech_amt_8            int64
 148  max_rech_amt_9            int64
 149  date_of_last_rech_6       object
 150  date_of_last_rech_7       object
 151  date_of_last_rech_8       object
 152  date_of_last_rech_9       object
 153  last_day_rch_amt_6        int64
 154  last_day_rch_amt_7        int64
 155  last_day_rch_amt_8        int64
 156  last_day_rch_amt_9        int64
 157  date_of_last_rech_data_6  object
 158  date_of_last_rech_data_7  object
 159  date_of_last_rech_data_8  object
 160  date_of_last_rech_data_9  object
 161  total_rech_data_6         float64
 162  total_rech_data_7         float64
 163  total_rech_data_8         float64
 164  total_rech_data_9         float64
 165  max_rech_data_6           float64
 166  max_rech_data_7           float64
 167  max_rech_data_8           float64
 168  max_rech_data_9           float64
 169  count_rech_2g_6           float64
 170  count_rech_2g_7           float64
 171  count_rech_2g_8           float64
 172  count_rech_2g_9           float64
 173  count_rech_3g_6           float64
 174  count_rech_3g_7           float64
 175  count_rech_3g_8           float64
 176  count_rech_3g_9           float64
 177  av_rech_amt_data_6        float64
 178  av_rech_amt_data_7        float64
 179  av_rech_amt_data_8        float64
 180  av_rech_amt_data_9        float64
 181  vol_2g_mb_6               float64
 182  vol_2g_mb_7               float64
 183  vol_2g_mb_8               float64
 184  vol_2g_mb_9               float64
 185  vol_3g_mb_6               float64
 186  vol_3g_mb_7               float64
 187  vol_3g_mb_8               float64
 188  vol_3g_mb_9               float64
 189  arpu_3g_6                 float64
 190  arpu_3g_7                 float64
 191  arpu_3g_8                 float64
 192  arpu_3g_9                 float64
 193  arpu_2g_6                 float64
 194  arpu_2g_7                 float64
 195  arpu_2g_8                 float64
 196  arpu_2g_9                 float64
 197  night_pck_user_6          float64
 198  night_pck_user_7          float64
 199  night_pck_user_8          float64
 200  night_pck_user_9          float64
 201  monthly_2g_6              int64
 202  monthly_2g_7              int64
 203  monthly_2g_8              int64
 204  monthly_2g_9              int64
 205  sachet_2g_6               int64
 206  sachet_2g_7               int64
 207  sachet_2g_8               int64
 208  sachet_2g_9               int64
 209  monthly_3g_6              int64
 210  monthly_3g_7              int64
 211  monthly_3g_8              int64
 212  monthly_3g_9              int64
 213  sachet_3g_6               int64
 214  sachet_3g_7               int64
 215  sachet_3g_8               int64
 216  sachet_3g_9               int64
 217  fb_user_6                 float64
 218  fb_user_7                 float64
 219  fb_user_8                 float64
 220  fb_user_9                 float64
 221  aon                       int64
 222  aug_vbc_3g                float64
 223  jul_vbc_3g                float64
 224  jun_vbc_3g                float64
 225  sep_vbc_3g                float64
dtypes: float64(179), int64(35), object(12)
memory usage: 172.4+ MB

In [7]:
#Let's examine the data's distribution.
df.describe().T

,count,mean,std,min,25%,50%,75%,max
mobile_number,99999.0,7.001207e+09,695669.386290,7.000000e+09,7.000606e+09,7.001205e+09,7.001812e+09,7.002411e+09
circle_id,99999.0,1.090000e+02,0.000000,1.090000e+02,1.090000e+02,1.090000e+02,1.090000e+02,1.090000e+02
loc_og_t2o_mou,98981.0,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
std_og_t2o_mou,98981.0,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
loc_ic_t2o_mou,98981.0,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
arpu_6,99999.0,2.829874e+02,328.439770,-2.258709e+03,9.341150e+01,1.977040e+02,3.710600e+02,2.773109e+04
arpu_7,99999.0,2.785366e+02,338.156291,-2.014045e+03,8.698050e+01,1.916400e+02,3.653445e+02,3.514583e+04
arpu_8,99999.0,2.791547e+02,344.474791,-9.458080e+02,8.412600e+01,1.920800e+02,3.693705e+02,3.354362e+04
arpu_9,99999.0,2.616451e+02,341.998630,-1.899505e+03,6.268500e+01,1.768490e+02,3.534665e+02,3.880562e+04
onnet_mou_6,96062.0,1.323959e+02,297.207406,0.000000e+00,7.380000e+00,3.431000e+01,1.187400e+02,7.376710e+03
onnet_mou_7,96140.0,1.336708e+02,308.794148,0.000000e+00,6.660000e+00,3.233000e+01,1.155950e+02,8.157780e+03
onnet_mou_8,94621.0,1.330181e+02,308.951589,0.000000e+00,6.460000e+00,3.236000e+01,1.158600e+02,1.075256e+04
onnet_mou_9,92254.0,1.303023e+02,308.477668,0.000000e+00,5.330000e+00,2.984000e+01,1.121300e+02,1.042746e+04
offnet_mou_6,96062.0,1.979356e+02,316.851613,0.000000e+00,3.473000e+01,9.631000e+01,2.318600e+02,8.362360e+03
offnet_mou_7,96140.0,1.970451e+02,325.862803,0.000000e+00,3.219000e+01,9.173500e+01,2.268150e+02,9.667130e+03
offnet_mou_8,94621.0,1.965748e+02,327.170662,0.000000e+00,3.163000e+01,9.214000e+01,2.282600e+02,1.400734e+04
offnet_mou_9,92254.0,1.903372e+02,319.396092,0.000000e+00,2.713000e+01,8.729000e+01,2.205050e+02,1.031076e+04
roam_ic_mou_6,96062.0,9.950013e+00,72.825411,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.372438e+04
roam_ic_mou_7,96140.0,7.149898e+00,73.447948,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.537104e+04
roam_ic_mou_8,94621.0,7.292981e+00,68.402466,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.309536e+04
roam_ic_mou_9,92254.0,6.343841e+00,57.137537,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,8.464030e+03
roam_og_mou_6,96062.0,1.391134e+01,71.443196,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.775110e+03
roam_og_mou_7,96140.0,9.818732e+00,58.455762,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.812040e+03
roam_og_mou_8,94621.0,9.971890e+00,64.713221,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.337040e+03
roam_og_mou_9,92254.0,8.555519e+00,58.438186,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.428460e+03
loc_og_t2t_mou_6,96062.0,4.710076e+01,150.856393,0.000000e+00,1.660000e+00,1.191000e+01,4.096000e+01,6.431330e+03
loc_og_t2t_mou_7,96140.0,4.647301e+01,155.318705,0.000000e+00,1.630000e+00,1.161000e+01,3.991000e+01,7.400660e+03
loc_og_t2t_mou_8,94621.0,4.588781e+01,151.184830,0.000000e+00,1.600000e+00,1.173000e+01,4.011000e+01,1.075256e+04
loc_og_t2t_mou_9,92254.0,4.458445e+01,147.995390,0.000000e+00,1.360000e+00,1.126000e+01,3.928000e+01,1.038924e+04
loc_og_t2m_mou_6,96062.0,9.334209e+01,162.780544,0.000000e+00,9.880000e+00,4.103000e+01,1.103900e+02,4.729740e+03
loc_og_t2m_mou_7,96140.0,9.139713e+01,157.492308,0.000000e+00,1.002500e+01,4.043000e+01,1.075600e+02,4.557140e+03
loc_og_t2m_mou_8,94621.0,9.175513e+01,156.537048,0.000000e+00,9.810000e+00,4.036000e+01,1.090900e+02,4.961330e+03
loc_og_t2m_mou_9,92254.0,9.046319e+01,158.681454,0.000000e+00,8.810000e+00,3.912000e+01,1.068100e+02,4.429880e+03
loc_og_t2f_mou_6,96062.0,3.751013e+00,14.230438,0.000000e+00,0.000000e+00,0.000000e+00,2.080000e+00,1.466030e+03
loc_og_t2f_mou_7,96140.0,3.792985e+00,14.264986,0.000000e+00,0.000000e+00,0.000000e+00,2.090000e+00,1.196430e+03
loc_og_t2f_mou_8,94621.0,3.677991e+00,13.270996,0.000000e+00,0.000000e+00,0.000000e+00,2.040000e+00,9.284900e+02
loc_og_t2f_mou_9,92254.0,3.655123e+00,13.457549,0.000000e+00,0.000000e+00,0.000000e+00,1.940000e+00,9.274100e+02
loc_og_t2c_mou_6,96062.0,1.123056e+00,5.448946,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.428600e+02
loc_og_t2c_mou_7,96140.0,1.368500e+00,7.533445,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,9.162400e+02
loc_og_t2c_mou_8,94621.0,1.433821e+00,6.783335,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.020900e+02
loc_og_t2c_mou_9,92254.0,1.232726e+00,5.619021,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.398400e+02
loc_og_mou_6,96062.0,1.442012e+02,251.751489,0.000000e+00,1.711000e+01,6.511000e+01,1.682700e+02,1.064338e+04
loc_og_mou_7,96140.0,1.416705e+02,248.731086,0.000000e+00,1.748000e+01,6.368500e+01,1.643825e+02,7.674780e+03
loc_og_mou_8,94621.0,1.413282e+02,245.914311,0.000000e+00,1.711000e+01,6.373000e+01,1.661100e+02,1.103991e+04
loc_og_mou_9,92254.0,1.387100e+02,245.934517,0.000000e+00,1.556000e+01,6.184000e+01,1.622250e+02,1.109926e+04
std_og_t2t_mou_6,96062.0,7.982987e+01,252.476533,0.000000e+00,0.000000e+00,0.000000e+00,3.080750e+01,7.366580e+03
std_og_t2t_mou_7,96140.0,8.329960e+01,263.631042,0.000000e+00,0.000000e+00,0.000000e+00,3.113250e+01,8.133660e+03
std_og_t2t_mou_8,94621.0,8.328267e+01,265.486090,0.000000e+00,0.000000e+00,0.000000e+00,3.058000e+01,8.014430e+03
std_og_t2t_mou_9,92254.0,8.234292e+01,267.184991,0.000000e+00,0.000000e+00,0.000000e+00,2.823000e+01,9.382580e+03
std_og_t2m_mou_6,96062.0,8.729962e+01,255.617850,0.000000e+00,0.000000e+00,3.950000e+00,5.329000e+01,8.314760e+03
std_og_t2m_mou_7,96140.0,9.080414e+01,269.347911,0.000000e+00,0.000000e+00,3.635000e+00,5.404000e+01,9.284740e+03
std_og_t2m_mou_8,94621.0,8.983839e+01,271.757783,0.000000e+00,0.000000e+00,3.310000e+00,5.249000e+01,1.395004e+04
std_og_t2m_mou_9,92254.0,8.627662e+01,261.407396,0.000000e+00,0.000000e+00,2.500000e+00,4.856000e+01,1.022343e+04
std_og_t2f_mou_6,96062.0,1.129011e+00,7.984970,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.285600e+02
std_og_t2f_mou_7,96140.0,1.115010e+00,8.599406,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.446300e+02
std_og_t2f_mou_8,94621.0,1.067792e+00,7.905971,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.169100e+02
std_og_t2f_mou_9,92254.0,1.042362e+00,8.261770,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,8.084900e+02
std_og_t2c_mou_6,96062.0,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
std_og_t2c_mou_7,96140.0,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
std_og_t2c_mou_8,94621.0,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
std_og_t2c_mou_9,92254.0,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
std_og_mou_6,96062.0,1.682612e+02,389.948499,0.000000e+00,0.000000e+00,1.164000e+01,1.448375e+02,8.432990e+03
std_og_mou_7,96140.0,1.752214e+02,408.922934,0.000000e+00,0.000000e+00,1.109000e+01,1.506150e+02,1.093673e+04
std_og_mou_8,94621.0,1.741915e+02,411.633049,0.000000e+00,0.000000e+00,1.041000e+01,1.479400e+02,1.398006e+04
std_og_mou_9,92254.0,1.696645e+02,405.138658,0.000000e+00,0.000000e+00,8.410000e+00,1.421050e+02,1.149531e+04
isd_og_mou_6,96062.0,7.982775e-01,25.765248,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.900660e+03
isd_og_mou_7,96140.0,7.765721e-01,25.603052,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.490280e+03
isd_og_mou_8,94621.0,7.912471e-01,25.544471,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.681540e+03
isd_og_mou_9,92254.0,7.238921e-01,21.310751,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.244530e+03
spl_og_mou_6,96062.0,3.916811e+00,14.936449,0.000000e+00,0.000000e+00,0.000000e+00,2.430000e+00,1.023210e+03
spl_og_mou_7,96140.0,4.978279e+00,20.661570,0.000000e+00,0.000000e+00,0.000000e+00,3.710000e+00,2.372510e+03
spl_og_mou_8,94621.0,5.053769e+00,17.855111,0.000000e+00,0.000000e+00,0.000000e+00,3.990000e+00,1.390880e+03
spl_og_mou_9,92254.0,4.412767e+00,16.328227,0.000000e+00,0.000000e+00,0.000000e+00,3.230000e+00,1.635710e+03
og_others_6,96062.0,4.541571e-01,4.125911,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,8.008900e+02
og_others_7,96140.0,3.023539e-02,2.161717,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.701300e+02
og_others_8,94621.0,3.337198e-02,2.323464,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.949300e+02
og_others_9,92254.0,4.745572e-02,3.635466,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,7.877900e+02
total_og_mou_6,99999.0,3.051334e+02,463.419481,0.000000e+00,4.474000e+01,1.451400e+02,3.728600e+02,1.067403e+04
total_og_mou_7,99999.0,3.102312e+02,480.031178,0.000000e+00,4.301000e+01,1.415300e+02,3.785700e+02,1.136531e+04
total_og_mou_8,99999.0,3.041195e+02,478.150031,0.000000e+00,3.858000e+01,1.386100e+02,3.699000e+02,1.404306e+04
total_og_mou_9,99999.0,2.892792e+02,468.980002,0.000000e+00,2.551000e+01,1.254600e+02,3.534800e+02,1.151773e+04
loc_ic_t2t_mou_6,96062.0,4.792237e+01,140.258485,0.000000e+00,2.990000e+00,1.569000e+01,4.684000e+01,6.626930e+03
loc_ic_t2t_mou_7,96140.0,4.799052e+01,145.795055,0.000000e+00,3.230000e+00,1.574000e+01,4.581000e+01,9.324660e+03
loc_ic_t2t_mou_8,94621.0,4.721136e+01,137.239552,0.000000e+00,3.280000e+00,1.603000e+01,4.629000e+01,1.069623e+04
loc_ic_t2t_mou_9,92254.0,4.628179e+01,140.130610,0.000000e+00,3.290000e+00,1.566000e+01,4.518000e+01,1.059883e+04
loc_ic_t2m_mou_6,96062.0,1.074757e+02,171.713903,0.000000e+00,1.729000e+01,5.649000e+01,1.323875e+02,4.693860e+03
loc_ic_t2m_mou_7,96140.0,1.071205e+02,169.423620,0.000000e+00,1.859000e+01,5.708000e+01,1.309600e+02,4.455830e+03
loc_ic_t2m_mou_8,94621.0,1.084605e+02,169.723759,0.000000e+00,1.893000e+01,5.824000e+01,1.339300e+02,6.274190e+03
loc_ic_t2m_mou_9,92254.0,1.061555e+02,165.492803,0.000000e+00,1.856000e+01,5.661000e+01,1.304900e+02,5.463780e+03
loc_ic_t2f_mou_6,96062.0,1.208430e+01,40.140895,0.000000e+00,0.000000e+00,8.800000e-01,8.140000e+00,1.872340e+03
loc_ic_t2f_mou_7,96140.0,1.259970e+01,42.977442,0.000000e+00,0.000000e+00,9.300000e-01,8.282500e+00,1.983010e+03
loc_ic_t2f_mou_8,94621.0,1.175183e+01,39.125379,0.000000e+00,0.000000e+00,9.300000e-01,8.110000e+00,2.433060e+03
loc_ic_t2f_mou_9,92254.0,1.217310e+01,43.840776,0.000000e+00,0.000000e+00,9.600000e-01,8.140000e+00,4.318280e+03
loc_ic_mou_6,96062.0,1.674911e+02,254.124029,0.000000e+00,3.039000e+01,9.216000e+01,2.080750e+02,7.454630e+03
loc_ic_mou_7,96140.0,1.677195e+02,256.242707,0.000000e+00,3.246000e+01,9.255000e+01,2.058375e+02,9.669910e+03
loc_ic_mou_8,94621.0,1.674326e+02,250.025523,0.000000e+00,3.274000e+01,9.383000e+01,2.072800e+02,1.083016e+04
loc_ic_mou_9,92254.0,1.646193e+02,249.845070,0.000000e+00,3.229000e+01,9.164000e+01,2.027375e+02,1.079629e+04
std_ic_t2t_mou_6,96062.0,9.575993e+00,54.330607,0.000000e+00,0.000000e+00,0.000000e+00,4.060000e+00,5.459560e+03
std_ic_t2t_mou_7,96140.0,1.001190e+01,57.411971,0.000000e+00,0.000000e+00,0.000000e+00,4.230000e+00,5.800930e+03
std_ic_t2t_mou_8,94621.0,9.883921e+00,55.073186,0.000000e+00,0.000000e+00,0.000000e+00,4.080000e+00,4.309290e+03
std_ic_t2t_mou_9,92254.0,9.432479e+00,53.376273,0.000000e+00,0.000000e+00,0.000000e+00,3.510000e+00,3.819830e+03
std_ic_t2m_mou_6,96062.0,2.072224e+01,80.793414,0.000000e+00,0.000000e+00,2.030000e+00,1.503000e+01,5.647160e+03
std_ic_t2m_mou_7,96140.0,2.165641e+01,86.521393,0.000000e+00,0.000000e+00,2.040000e+00,1.574000e+01,6.141880e+03
std_ic_t2m_mou_8,94621.0,2.118321e+01,83.683565,0.000000e+00,0.000000e+00,2.030000e+00,1.536000e+01,5.645860e+03
std_ic_t2m_mou_9,92254.0,1.962091e+01,74.913050,0.000000e+00,0.000000e+00,1.740000e+00,1.426000e+01,5.689760e+03
std_ic_t2f_mou_6,96062.0,2.156397e+00,16.495594,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.351110e+03
std_ic_t2f_mou_7,96140.0,2.216923e+00,16.454061,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.136080e+03
std_ic_t2f_mou_8,94621.0,2.085004e+00,15.812580,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.394890e+03
std_ic_t2f_mou_9,92254.0,2.173419e+00,15.978601,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.431960e+03
std_ic_t2o_mou_6,96062.0,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
std_ic_t2o_mou_7,96140.0,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
std_ic_t2o_mou_8,94621.0,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
std_ic_t2o_mou_9,92254.0,0.000000e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
std_ic_mou_6,96062.0,3.245718e+01,106.283386,0.000000e+00,0.000000e+00,5.890000e+00,2.693000e+01,5.712110e+03
std_ic_mou_7,96140.0,3.388783e+01,113.720168,0.000000e+00,0.000000e+00,5.960000e+00,2.831000e+01,6.745760e+03
std_ic_mou_8,94621.0,3.315474e+01,110.127008,0.000000e+00,1.000000e-02,5.880000e+00,2.771000e+01,5.957140e+03
std_ic_mou_9,92254.0,3.122934e+01,101.982303,0.000000e+00,0.000000e+00,5.380000e+00,2.569000e+01,5.956660e+03
total_ic_mou_6,99999.0,2.001300e+02,291.651671,0.000000e+00,3.853000e+01,1.147400e+02,2.516700e+02,7.716140e+03
total_ic_mou_7,99999.0,2.028531e+02,298.124954,0.000000e+00,4.119000e+01,1.163400e+02,2.506600e+02,9.699010e+03
total_ic_mou_8,99999.0,1.987508e+02,289.321094,0.000000e+00,3.829000e+01,1.146600e+02,2.489900e+02,1.083038e+04
total_ic_mou_9,99999.0,1.892143e+02,284.823024,0.000000e+00,3.237000e+01,1.058900e+02,2.363200e+02,1.079659e+04
spl_ic_mou_6,96062.0,6.155660e-02,0.160920,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.976000e+01
spl_ic_mou_7,96140.0,3.358477e-02,0.155725,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.133000e+01
spl_ic_mou_8,94621.0,4.036134e-02,0.146147,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.686000e+01
spl_ic_mou_9,92254.0,1.631370e-01,0.527860,0.000000e+00,0.000000e+00,0.000000e+00,6.000000e-02,6.238000e+01
isd_ic_mou_6,96062.0,7.460608e+00,59.722948,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,6.789410e+03
isd_ic_mou_7,96140.0,8.334936e+00,65.219829,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.289540e+03
isd_ic_mou_8,94621.0,8.442001e+00,63.813098,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.127010e+03
isd_ic_mou_9,92254.0,8.063003e+00,63.505379,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.057740e+03
ic_others_6,96062.0,8.546555e-01,11.955164,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.362940e+03
ic_others_7,96140.0,1.012960e+00,12.673099,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.495940e+03
ic_others_8,94621.0,9.708005e-01,13.284348,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.327510e+03
ic_others_9,92254.0,1.017162e+00,12.381172,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.005230e+03
total_rech_num_6,99999.0,7.558806e+00,7.078405,0.000000e+00,3.000000e+00,6.000000e+00,9.000000e+00,3.070000e+02
total_rech_num_7,99999.0,7.700367e+00,7.070422,0.000000e+00,3.000000e+00,6.000000e+00,1.000000e+01,1.380000e+02
total_rech_num_8,99999.0,7.212912e+00,7.203753,0.000000e+00,3.000000e+00,5.000000e+00,9.000000e+00,1.960000e+02
total_rech_num_9,99999.0,6.893019e+00,7.096261,0.000000e+00,3.000000e+00,5.000000e+00,9.000000e+00,1.310000e+02
total_rech_amt_6,99999.0,3.275146e+02,398.019701,0.000000e+00,1.090000e+02,2.300000e+02,4.375000e+02,3.519000e+04
total_rech_amt_7,99999.0,3.229630e+02,408.114237,0.000000e+00,1.000000e+02,2.200000e+02,4.280000e+02,4.033500e+04
total_rech_amt_8,99999.0,3.241571e+02,416.540455,0.000000e+00,9.000000e+01,2.250000e+02,4.345000e+02,4.532000e+04
total_rech_amt_9,99999.0,3.033457e+02,404.588583,0.000000e+00,5.200000e+01,2.000000e+02,4.150000e+02,3.723500e+04
max_rech_amt_6,99999.0,1.046375e+02,120.614894,0.000000e+00,3.000000e+01,1.100000e+02,1.200000e+02,4.010000e+03
max_rech_amt_7,99999.0,1.047524e+02,124.523970,0.000000e+00,3.000000e+01,1.100000e+02,1.280000e+02,4.010000e+03
max_rech_amt_8,99999.0,1.077282e+02,126.902505,0.000000e+00,3.000000e+01,9.800000e+01,1.440000e+02,4.449000e+03
max_rech_amt_9,99999.0,1.019439e+02,125.375109,0.000000e+00,2.800000e+01,6.100000e+01,1.440000e+02,3.399000e+03
last_day_rch_amt_6,99999.0,6.315625e+01,97.356649,0.000000e+00,0.000000e+00,3.000000e+01,1.100000e+02,4.010000e+03
last_day_rch_amt_7,99999.0,5.938580e+01,95.915385,0.000000e+00,0.000000e+00,3.000000e+01,1.100000e+02,4.010000e+03
last_day_rch_amt_8,99999.0,6.264172e+01,104.431816,0.000000e+00,0.000000e+00,3.000000e+01,1.300000e+02,4.449000e+03
last_day_rch_amt_9,99999.0,4.390125e+01,90.809712,0.000000e+00,0.000000e+00,0.000000e+00,5.000000e+01,3.399000e+03
total_rech_data_6,25153.0,2.463802e+00,2.789128,1.000000e+00,1.000000e+00,1.000000e+00,3.000000e+00,6.100000e+01
total_rech_data_7,25571.0,2.666419e+00,3.031593,1.000000e+00,1.000000e+00,1.000000e+00,3.000000e+00,5.400000e+01
total_rech_data_8,26339.0,2.651999e+00,3.074987,1.000000e+00,1.000000e+00,1.000000e+00,3.000000e+00,6.000000e+01
total_rech_data_9,25922.0,2.441170e+00,2.516339,1.000000e+00,1.000000e+00,2.000000e+00,3.000000e+00,8.400000e+01
max_rech_data_6,25153.0,1.263934e+02,108.477235,1.000000e+00,2.500000e+01,1.450000e+02,1.770000e+02,1.555000e+03
max_rech_data_7,25571.0,1.267295e+02,109.765267,1.000000e+00,2.500000e+01,1.450000e+02,1.770000e+02,1.555000e+03
max_rech_data_8,26339.0,1.257173e+02,109.437851,1.000000e+00,2.500000e+01,1.450000e+02,1.790000e+02,1.555000e+03
max_rech_data_9,25922.0,1.249414e+02,111.363760,1.000000e+00,2.500000e+01,1.450000e+02,1.790000e+02,1.555000e+03
count_rech_2g_6,25153.0,1.864668e+00,2.570254,0.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,4.200000e+01
count_rech_2g_7,25571.0,2.044699e+00,2.768332,0.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,4.800000e+01
count_rech_2g_8,26339.0,2.016288e+00,2.720132,0.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,4.400000e+01
count_rech_2g_9,25922.0,1.781807e+00,2.214701,0.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,4.000000e+01
count_rech_3g_6,25153.0,5.991333e-01,1.274428,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,2.900000e+01
count_rech_3g_7,25571.0,6.217199e-01,1.394524,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,3.500000e+01
count_rech_3g_8,26339.0,6.357113e-01,1.422827,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,4.500000e+01
count_rech_3g_9,25922.0,6.593627e-01,1.411513,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,4.900000e+01
av_rech_amt_data_6,25153.0,1.926010e+02,192.646318,1.000000e+00,8.200000e+01,1.540000e+02,2.520000e+02,7.546000e+03
av_rech_amt_data_7,25571.0,2.009813e+02,196.791224,5.000000e-01,9.200000e+01,1.540000e+02,2.520000e+02,4.365000e+03
av_rech_amt_data_8,26339.0,1.975265e+02,191.301305,5.000000e-01,8.700000e+01,1.540000e+02,2.520000e+02,4.076000e+03
av_rech_amt_data_9,25922.0,1.927343e+02,188.400286,1.000000e+00,6.900000e+01,1.640000e+02,2.520000e+02,4.061000e+03
vol_2g_mb_6,99999.0,5.190496e+01,213.356445,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.028590e+04
vol_2g_mb_7,99999.0,5.122994e+01,212.302217,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,7.873550e+03
vol_2g_mb_8,99999.0,5.017015e+01,212.347892,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.111761e+04
vol_2g_mb_9,99999.0,4.471970e+01,198.653570,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,8.993950e+03
vol_3g_mb_6,99999.0,1.213962e+02,544.247227,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.573540e+04
vol_3g_mb_7,99999.0,1.289958e+02,541.494013,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.814412e+04
vol_3g_mb_8,99999.0,1.354107e+02,558.775335,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.003606e+04
vol_3g_mb_9,99999.0,1.360566e+02,577.394194,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.922127e+04
arpu_3g_6,25153.0,8.955506e+01,193.124653,-3.082000e+01,0.000000e+00,4.800000e-01,1.220700e+02,6.362280e+03
arpu_3g_7,25571.0,8.938412e+01,195.893924,-2.604000e+01,0.000000e+00,4.200000e-01,1.195600e+02,4.980900e+03

# 2. Data Cleaning

Some columns representing volume-based users include the month in their names, whereas the remaining columns use the numerals "6,7,8" to indicate the month. I am planning to rename the missplead column.

In [8]:
month = ['aug_vbc_3g','jul_vbc_3g','jun_vbc_3g','sep_vbc_3g']
df = df.rename(columns = {'aug_vbc_3g':'vbc_3g_8','jul_vbc_3g':'vbc_3g_7','jun_vbc_3g':'vbc_3g_6',
                          'sep_vbc_3g':'vbc_3g_9'})

## 2.1 Converting Datetime

In [9]:
#The conversion of date columns to date-time format

date_col= [col for col in df.columns if 'date' in col]

for i in df[date_col]:
    df[i] = pd.to_datetime(df[i])

In [10]:
df.info(verbose=1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99999 entries, 0 to 99998
Data columns (total 226 columns):
 #    Column                    Dtype
---   ------                    -----
 0    mobile_number             int64
 1    circle_id                 int64
 2    loc_og_t2o_mou            float64
 3    std_og_t2o_mou            float64
 4    loc_ic_t2o_mou            float64
 5    last_date_of_month_6      datetime64[ns]
 6    last_date_of_month_7      datetime64[ns]
 7    last_date_of_month_8      datetime64[ns]
 8    last_date_of_month_9      datetime64[ns]
 9    arpu_6                    float64
 10   arpu_7                    float64
 11   arpu_8                    float64
 12   arpu_9                    float64
 13   onnet_mou_6               float64
 14   onnet_mou_7               float64
 15   onnet_mou_8               float64
 16   onnet_mou_9               float64
 17   offnet_mou_6              float64
 18   offnet_mou_7              float64
 19   offnet_mou_8              float64
 20   offnet_mou_9              float64
 21   roam_ic_mou_6             float64
 22   roam_ic_mou_7             float64
 23   roam_ic_mou_8             float64
 24   roam_ic_mou_9             float64
 25   roam_og_mou_6             float64
 26   roam_og_mou_7             float64
 27   roam_og_mou_8             float64
 28   roam_og_mou_9             float64
 29   loc_og_t2t_mou_6          float64
 30   loc_og_t2t_mou_7          float64
 31   loc_og_t2t_mou_8          float64
 32   loc_og_t2t_mou_9          float64
 33   loc_og_t2m_mou_6          float64
 34   loc_og_t2m_mou_7          float64
 35   loc_og_t2m_mou_8          float64
 36   loc_og_t2m_mou_9          float64
 37   loc_og_t2f_mou_6          float64
 38   loc_og_t2f_mou_7          float64
 39   loc_og_t2f_mou_8          float64
 40   loc_og_t2f_mou_9          float64
 41   loc_og_t2c_mou_6          float64
 42   loc_og_t2c_mou_7          float64
 43   loc_og_t2c_mou_8          float64
 44   loc_og_t2c_mou_9          float64
 45   loc_og_mou_6              float64
 46   loc_og_mou_7              float64
 47   loc_og_mou_8              float64
 48   loc_og_mou_9              float64
 49   std_og_t2t_mou_6          float64
 50   std_og_t2t_mou_7          float64
 51   std_og_t2t_mou_8          float64
 52   std_og_t2t_mou_9          float64
 53   std_og_t2m_mou_6          float64
 54   std_og_t2m_mou_7          float64
 55   std_og_t2m_mou_8          float64
 56   std_og_t2m_mou_9          float64
 57   std_og_t2f_mou_6          float64
 58   std_og_t2f_mou_7          float64
 59   std_og_t2f_mou_8          float64
 60   std_og_t2f_mou_9          float64
 61   std_og_t2c_mou_6          float64
 62   std_og_t2c_mou_7          float64
 63   std_og_t2c_mou_8          float64
 64   std_og_t2c_mou_9          float64
 65   std_og_mou_6              float64
 66   std_og_mou_7              float64
 67   std_og_mou_8              float64
 68   std_og_mou_9              float64
 69   isd_og_mou_6              float64
 70   isd_og_mou_7              float64
 71   isd_og_mou_8              float64
 72   isd_og_mou_9              float64
 73   spl_og_mou_6              float64
 74   spl_og_mou_7              float64
 75   spl_og_mou_8              float64
 76   spl_og_mou_9              float64
 77   og_others_6               float64
 78   og_others_7               float64
 79   og_others_8               float64
 80   og_others_9               float64
 81   total_og_mou_6            float64
 82   total_og_mou_7            float64
 83   total_og_mou_8            float64
 84   total_og_mou_9            float64
 85   loc_ic_t2t_mou_6          float64
 86   loc_ic_t2t_mou_7          float64
 87   loc_ic_t2t_mou_8          float64
 88   loc_ic_t2t_mou_9          float64
 89   loc_ic_t2m_mou_6          float64
 90   loc_ic_t2m_mou_7          float64
 91   loc_ic_t2m_mou_8          float64
 92   loc_ic_t2m_mou_9          float64
 93   loc_ic_t2f_mou_6          float64
 94   loc_ic_t2f_mou_7          float64
 95   loc_ic_t2f_mou_8          float64
 96   loc_ic_t2f_mou_9          float64
 97   loc_ic_mou_6              float64
 98   loc_ic_mou_7              float64
 99   loc_ic_mou_8              float64
 100  loc_ic_mou_9              float64
 101  std_ic_t2t_mou_6          float64
 102  std_ic_t2t_mou_7          float64
 103  std_ic_t2t_mou_8          float64
 104  std_ic_t2t_mou_9          float64
 105  std_ic_t2m_mou_6          float64
 106  std_ic_t2m_mou_7          float64
 107  std_ic_t2m_mou_8          float64
 108  std_ic_t2m_mou_9          float64
 109  std_ic_t2f_mou_6          float64
 110  std_ic_t2f_mou_7          float64
 111  std_ic_t2f_mou_8          float64
 112  std_ic_t2f_mou_9          float64
 113  std_ic_t2o_mou_6          float64
 114  std_ic_t2o_mou_7          float64
 115  std_ic_t2o_mou_8          float64
 116  std_ic_t2o_mou_9          float64
 117  std_ic_mou_6              float64
 118  std_ic_mou_7              float64
 119  std_ic_mou_8              float64
 120  std_ic_mou_9              float64
 121  total_ic_mou_6            float64
 122  total_ic_mou_7            float64
 123  total_ic_mou_8            float64
 124  total_ic_mou_9            float64
 125  spl_ic_mou_6              float64
 126  spl_ic_mou_7              float64
 127  spl_ic_mou_8              float64
 128  spl_ic_mou_9              float64
 129  isd_ic_mou_6              float64
 130  isd_ic_mou_7              float64
 131  isd_ic_mou_8              float64
 132  isd_ic_mou_9              float64
 133  ic_others_6               float64
 134  ic_others_7               float64
 135  ic_others_8               float64
 136  ic_others_9               float64
 137  total_rech_num_6          int64
 138  total_rech_num_7          int64
 139  total_rech_num_8          int64
 140  total_rech_num_9          int64
 141  total_rech_amt_6          int64
 142  total_rech_amt_7          int64
 143  total_rech_amt_8          int64
 144  total_rech_amt_9          int64
 145  max_rech_amt_6            int64
 146  max_rech_amt_7            int64
 147  max_rech_amt_8            int64
 148  max_rech_amt_9            int64
 149  date_of_last_rech_6       datetime64[ns]
 150  date_of_last_rech_7       datetime64[ns]
 151  date_of_last_rech_8       datetime64[ns]
 152  date_of_last_rech_9       datetime64[ns]
 153  last_day_rch_amt_6        int64
 154  last_day_rch_amt_7        int64
 155  last_day_rch_amt_8        int64
 156  last_day_rch_amt_9        int64
 157  date_of_last_rech_data_6  datetime64[ns]
 158  date_of_last_rech_data_7  datetime64[ns]
 159  date_of_last_rech_data_8  datetime64[ns]
 160  date_of_last_rech_data_9  datetime64[ns]
 161  total_rech_data_6         float64
 162  total_rech_data_7         float64
 163  total_rech_data_8         float64
 164  total_rech_data_9         float64
 165  max_rech_data_6           float64
 166  max_rech_data_7           float64
 167  max_rech_data_8           float64
 168  max_rech_data_9           float64
 169  count_rech_2g_6           float64
 170  count_rech_2g_7           float64
 171  count_rech_2g_8           float64
 172  count_rech_2g_9           float64
 173  count_rech_3g_6           float64
 174  count_rech_3g_7           float64
 175  count_rech_3g_8           float64
 176  count_rech_3g_9           float64
 177  av_rech_amt_data_6        float64
 178  av_rech_amt_data_7        float64
 179  av_rech_amt_data_8        float64
 180  av_rech_amt_data_9        float64
 181  vol_2g_mb_6               float64
 182  vol_2g_mb_7               float64
 183  vol_2g_mb_8               float64
 184  vol_2g_mb_9               float64
 185  vol_3g_mb_6               float64
 186  vol_3g_mb_7               float64
 187  vol_3g_mb_8               float64
 188  vol_3g_mb_9               float64
 189  arpu_3g_6                 float64
 190  arpu_3g_7                 float64
 191  arpu_3g_8                 float64
 192  arpu_3g_9                 float64
 193  arpu_2g_6                 float64
 194  arpu_2g_7                 float64
 195  arpu_2g_8                 float64
 196  arpu_2g_9                 float64
 197  night_pck_user_6          float64
 198  night_pck_user_7          float64
 199  night_pck_user_8          float64
 200  night_pck_user_9          float64
 201  monthly_2g_6              int64
 202  monthly_2g_7              int64
 203  monthly_2g_8              int64
 204  monthly_2g_9              int64
 205  sachet_2g_6               int64
 206  sachet_2g_7               int64
 207  sachet_2g_8               int64
 208  sachet_2g_9               int64
 209  monthly_3g_6              int64
 210  monthly_3g_7              int64
 211  monthly_3g_8              int64
 212  monthly_3g_9              int64
 213  sachet_3g_6               int64
 214  sachet_3g_7               int64
 215  sachet_3g_8               int64
 216  sachet_3g_9               int64
 217  fb_user_6                 float64
 218  fb_user_7                 float64
 219  fb_user_8                 float64
 220  fb_user_9                 float64
 221  aon                       int64
 222  vbc_3g_8                  float64
 223  vbc_3g_7                  float64
 224  vbc_3g_6                  float64
 225  vbc_3g_9                  float64
dtypes: datetime64[ns](12), float64(179), int64(35)
memory usage: 172.4 MB

# 2.2 Removing single unique value
Columns with a single unique value for all clients are essentially meaningless. As a result, i am deleting columns with zero variance from the dataset.

In [11]:
cols = []
for i in df.columns:
    if df[i].nunique() ==1:
        cols.append(i)
df = df.drop(cols,axis=1)
df.sample(2)

,mobile_number,arpu_6,arpu_7,arpu_8,arpu_9,onnet_mou_6,onnet_mou_7,onnet_mou_8,onnet_mou_9,offnet_mou_6,offnet_mou_7,offnet_mou_8,offnet_mou_9,roam_ic_mou_6,roam_ic_mou_7,roam_ic_mou_8,roam_ic_mou_9,roam_og_mou_6,roam_og_mou_7,roam_og_mou_8,roam_og_mou_9,loc_og_t2t_mou_6,loc_og_t2t_mou_7,loc_og_t2t_mou_8,loc_og_t2t_mou_9,loc_og_t2m_mou_6,loc_og_t2m_mou_7,loc_og_t2m_mou_8,loc_og_t2m_mou_9,loc_og_t2f_mou_6,loc_og_t2f_mou_7,loc_og_t2f_mou_8,loc_og_t2f_mou_9,loc_og_t2c_mou_6,loc_og_t2c_mou_7,loc_og_t2c_mou_8,loc_og_t2c_mou_9,loc_og_mou_6,loc_og_mou_7,loc_og_mou_8,loc_og_mou_9,std_og_t2t_mou_6,std_og_t2t_mou_7,std_og_t2t_mou_8,std_og_t2t_mou_9,std_og_t2m_mou_6,std_og_t2m_mou_7,std_og_t2m_mou_8,std_og_t2m_mou_9,std_og_t2f_mou_6,std_og_t2f_mou_7,std_og_t2f_mou_8,std_og_t2f_mou_9,std_og_mou_6,std_og_mou_7,std_og_mou_8,std_og_mou_9,isd_og_mou_6,isd_og_mou_7,isd_og_mou_8,isd_og_mou_9,spl_og_mou_6,spl_og_mou_7,spl_og_mou_8,spl_og_mou_9,og_others_6,og_others_7,og_others_8,og_others_9,total_og_mou_6,total_og_mou_7,total_og_mou_8,total_og_mou_9,loc_ic_t2t_mou_6,loc_ic_t2t_mou_7,loc_ic_t2t_mou_8,loc_ic_t2t_mou_9,loc_ic_t2m_mou_6,loc_ic_t2m_mou_7,loc_ic_t2m_mou_8,loc_ic_t2m_mou_9,loc_ic_t2f_mou_6,loc_ic_t2f_mou_7,loc_ic_t2f_mou_8,loc_ic_t2f_mou_9,loc_ic_mou_6,loc_ic_mou_7,loc_ic_mou_8,loc_ic_mou_9,std_ic_t2t_mou_6,std_ic_t2t_mou_7,std_ic_t2t_mou_8,std_ic_t2t_mou_9,std_ic_t2m_mou_6,std_ic_t2m_mou_7,std_ic_t2m_mou_8,std_ic_t2m_mou_9,std_ic_t2f_mou_6,std_ic_t2f_mou_7,std_ic_t2f_mou_8,std_ic_t2f_mou_9,std_ic_mou_6,std_ic_mou_7,std_ic_mou_8,std_ic_mou_9,total_ic_mou_6,total_ic_mou_7,total_ic_mou_8,total_ic_mou_9,spl_ic_mou_6,spl_ic_mou_7,spl_ic_mou_8,spl_ic_mou_9,isd_ic_mou_6,isd_ic_mou_7,isd_ic_mou_8,isd_ic_mou_9,ic_others_6,ic_others_7,ic_others_8,ic_others_9,total_rech_num_6,total_rech_num_7,total_rech_num_8,total_rech_num_9,total_rech_amt_6,total_rech_amt_7,total_rech_amt_8,total_rech_amt_9,max_rech_amt_6,max_rech_amt_7,max_rech_amt_8,max_rech_amt_9,date_of_last_rech_6,date_of_last_rech_7,date_of_last_rech_8,date_of_last_rech_9,last_day_rch_amt_6,last_day_rch_amt_7,last_day_rch_amt_8,last_day_rch_amt_9,date_of_last_rech_data_6,date_of_last_rech_data_7,date_of_last_rech_data_8,date_of_last_rech_data_9,total_rech_data_6,total_rech_data_7,total_rech_data_8,total_rech_data_9,max_rech_data_6,max_rech_data_7,max_rech_data_8,max_rech_data_9,count_rech_2g_6,count_rech_2g_7,count_rech_2g_8,count_rech_2g_9,count_rech_3g_6,count_rech_3g_7,count_rech_3g_8,count_rech_3g_9,av_rech_amt_data_6,av_rech_amt_data_7,av_rech_amt_data_8,av_rech_amt_data_9,vol_2g_mb_6,vol_2g_mb_7,vol_2g_mb_8,vol_2g_mb_9,vol_3g_mb_6,vol_3g_mb_7,vol_3g_mb_8,vol_3g_mb_9,arpu_3g_6,arpu_3g_7,arpu_3g_8,arpu_3g_9,arpu_2g_6,arpu_2g_7,arpu_2g_8,arpu_2g_9,night_pck_user_6,night_pck_user_7,night_pck_user_8,night_pck_user_9,monthly_2g_6,monthly_2g_7,monthly_2g_8,monthly_2g_9,sachet_2g_6,sachet_2g_7,sachet_2g_8,sachet_2g_9,monthly_3g_6,monthly_3g_7,monthly_3g_8,monthly_3g_9,sachet_3g_6,sachet_3g_7,sachet_3g_8,sachet_3g_9,fb_user_6,fb_user_7,fb_user_8,fb_user_9,aon,vbc_3g_8,vbc_3g_7,vbc_3g_6,vbc_3g_9
70246,7000965690,422.317,338.046,476.039,426.563,228.34,181.91,342.86,225.04,171.29,126.84,114.99,189.83,0.0,0.00,0.00,0.00,0.0,0.00,0.00,0.00,77.18,63.94,72.68,60.23,53.94,42.23,66.56,64.71,0.0,0.0,0.0,0.0,0.0,4.36,8.43,0.11,131.13,106.18,139.24,124.94,151.16,117.96,270.18,164.81,117.34,84.61,48.43,125.11,0.0,0.0,0.0,0.0,268.51,202.58,318.61,289.93,0.0,0.0,0.0,0.0,0.0,5.33,10.64,0.73,0.0,0.0,0.0,0.0,399.64,314.09,468.51,415.61,42.04,35.28,110.99,113.59,334.33,355.73,199.06,244.76,0.0,0.0,2.16,0.0,376.38,391.01,312.23,358.36,654.88,109.03,110.19,93.91,190.14,128.64,207.78,118.09,0.0,0.0,0.0,0.0,845.03,237.68,317.98,212.01,1221.41,628.69,630.21,570.38,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27,26,22,18,490,370,567,515,30,30,130,50,2014-06-29,2014-07-28,2014-08-31,2014-09-27,20,10,30,0,NaT,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,1429,0.0,0.0,0.0,0.0
15289,7000391649,123.511,41.810,45.330,46.250,12.84,0.00,0.40,0.00,229.09,15.83,29.13,30.49,0.0,23.69,8.18,4.88,0.0,15.83,29.53,30.49,12.84,0.00,0.00,0.00,11.51,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,24.36,0.00,0.00,0.00,0.00,0.00,0.00,0.00,217.58,0.00,0.00,0.00,0.0,0.0,0.0,0.0,217.58,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,241.94,0.00,0.00,0.00,14.58,0.23,0.00,0.00,9.66,0.00,0.00,0.00,0.0,0.0,0.00,0.0,24.24,0.23,0.00,0.00,0.00,0.00,0.00,0.00,44.96,0.00,0.00,0.00,0.0,0.0,0.0,0.0,44.96,0.00,0.00,0.00,69.21,0.23,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5,3,4,2,266,0,0,0,120,0,0,0,2014-06-30,2014-07-25,2014-08-26,2014-09-28,110,0,0,0,NaT,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,657,0.0,0.0,0.0,0.0

In [12]:
df.shape

(99999, 210)

`Observation`: Number of columns: unique column 16 is dropped from 226 to 210.

# 2.3 Create ID for each customer

Eliminate the mobile number column and create an id column for client identification.

In [13]:
#drop mobile number
df = df.drop('mobile_number', axis=1)

#Create id
df = df.reset_index()
df = df.rename(columns = {'index':'cust_id'})
df['cust_id'] = df['cust_id']+1
df.sample(2)

,cust_id,arpu_6,arpu_7,arpu_8,arpu_9,onnet_mou_6,onnet_mou_7,onnet_mou_8,onnet_mou_9,offnet_mou_6,offnet_mou_7,offnet_mou_8,offnet_mou_9,roam_ic_mou_6,roam_ic_mou_7,roam_ic_mou_8,roam_ic_mou_9,roam_og_mou_6,roam_og_mou_7,roam_og_mou_8,roam_og_mou_9,loc_og_t2t_mou_6,loc_og_t2t_mou_7,loc_og_t2t_mou_8,loc_og_t2t_mou_9,loc_og_t2m_mou_6,loc_og_t2m_mou_7,loc_og_t2m_mou_8,loc_og_t2m_mou_9,loc_og_t2f_mou_6,loc_og_t2f_mou_7,loc_og_t2f_mou_8,loc_og_t2f_mou_9,loc_og_t2c_mou_6,loc_og_t2c_mou_7,loc_og_t2c_mou_8,loc_og_t2c_mou_9,loc_og_mou_6,loc_og_mou_7,loc_og_mou_8,loc_og_mou_9,std_og_t2t_mou_6,std_og_t2t_mou_7,std_og_t2t_mou_8,std_og_t2t_mou_9,std_og_t2m_mou_6,std_og_t2m_mou_7,std_og_t2m_mou_8,std_og_t2m_mou_9,std_og_t2f_mou_6,std_og_t2f_mou_7,std_og_t2f_mou_8,std_og_t2f_mou_9,std_og_mou_6,std_og_mou_7,std_og_mou_8,std_og_mou_9,isd_og_mou_6,isd_og_mou_7,isd_og_mou_8,isd_og_mou_9,spl_og_mou_6,spl_og_mou_7,spl_og_mou_8,spl_og_mou_9,og_others_6,og_others_7,og_others_8,og_others_9,total_og_mou_6,total_og_mou_7,total_og_mou_8,total_og_mou_9,loc_ic_t2t_mou_6,loc_ic_t2t_mou_7,loc_ic_t2t_mou_8,loc_ic_t2t_mou_9,loc_ic_t2m_mou_6,loc_ic_t2m_mou_7,loc_ic_t2m_mou_8,loc_ic_t2m_mou_9,loc_ic_t2f_mou_6,loc_ic_t2f_mou_7,loc_ic_t2f_mou_8,loc_ic_t2f_mou_9,loc_ic_mou_6,loc_ic_mou_7,loc_ic_mou_8,loc_ic_mou_9,std_ic_t2t_mou_6,std_ic_t2t_mou_7,std_ic_t2t_mou_8,std_ic_t2t_mou_9,std_ic_t2m_mou_6,std_ic_t2m_mou_7,std_ic_t2m_mou_8,std_ic_t2m_mou_9,std_ic_t2f_mou_6,std_ic_t2f_mou_7,std_ic_t2f_mou_8,std_ic_t2f_mou_9,std_ic_mou_6,std_ic_mou_7,std_ic_mou_8,std_ic_mou_9,total_ic_mou_6,total_ic_mou_7,total_ic_mou_8,total_ic_mou_9,spl_ic_mou_6,spl_ic_mou_7,spl_ic_mou_8,spl_ic_mou_9,isd_ic_mou_6,isd_ic_mou_7,isd_ic_mou_8,isd_ic_mou_9,ic_others_6,ic_others_7,ic_others_8,ic_others_9,total_rech_num_6,total_rech_num_7,total_rech_num_8,total_rech_num_9,total_rech_amt_6,total_rech_amt_7,total_rech_amt_8,total_rech_amt_9,max_rech_amt_6,max_rech_amt_7,max_rech_amt_8,max_rech_amt_9,date_of_last_rech_6,date_of_last_rech_7,date_of_last_rech_8,date_of_last_rech_9,last_day_rch_amt_6,last_day_rch_amt_7,last_day_rch_amt_8,last_day_rch_amt_9,date_of_last_rech_data_6,date_of_last_rech_data_7,date_of_last_rech_data_8,date_of_last_rech_data_9,total_rech_data_6,total_rech_data_7,total_rech_data_8,total_rech_data_9,max_rech_data_6,max_rech_data_7,max_rech_data_8,max_rech_data_9,count_rech_2g_6,count_rech_2g_7,count_rech_2g_8,count_rech_2g_9,count_rech_3g_6,count_rech_3g_7,count_rech_3g_8,count_rech_3g_9,av_rech_amt_data_6,av_rech_amt_data_7,av_rech_amt_data_8,av_rech_amt_data_9,vol_2g_mb_6,vol_2g_mb_7,vol_2g_mb_8,vol_2g_mb_9,vol_3g_mb_6,vol_3g_mb_7,vol_3g_mb_8,vol_3g_mb_9,arpu_3g_6,arpu_3g_7,arpu_3g_8,arpu_3g_9,arpu_2g_6,arpu_2g_7,arpu_2g_8,arpu_2g_9,night_pck_user_6,night_pck_user_7,night_pck_user_8,night_pck_user_9,monthly_2g_6,monthly_2g_7,monthly_2g_8,monthly_2g_9,sachet_2g_6,sachet_2g_7,sachet_2g_8,sachet_2g_9,monthly_3g_6,monthly_3g_7,monthly_3g_8,monthly_3g_9,sachet_3g_6,sachet_3g_7,sachet_3g_8,sachet_3g_9,fb_user_6,fb_user_7,fb_user_8,fb_user_9,aon,vbc_3g_8,vbc_3g_7,vbc_3g_6,vbc_3g_9
53873,53874,105.358,120.532,151.441,174.51,182.88,114.21,187.23,298.53,22.96,35.39,33.19,17.94,0.00,0.0,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.96,4.61,9.79,6.34,12.71,25.24,8.78,0.00,0.71,0.0,0.51,0.00,0.26,0.0,0.06,6.34,14.39,29.86,19.09,182.88,113.24,182.61,288.73,16.61,16.64,7.94,7.93,0.0,0.0,0.0,0.0,199.49,129.89,190.56,296.66,0.0,0.0,0.0,0.0,0.00,5.98,0.73,4.83,0.43,0.0,0.0,0.0,206.28,150.28,221.16,320.59,1.88,12.28,10.78,46.14,55.66,51.08,56.68,70.74,14.69,116.19,102.96,59.33,72.24,179.56,170.43,176.23,117.29,179.33,184.71,78.08,10.69,20.04,15.03,16.61,0.0,0.0,0.01,0.0,127.99,199.38,199.76,94.69,206.24,379.31,370.44,273.26,0.0,0.0,0.25,1.33,0.0,0.0,0.0,0.0,5.99,0.36,0.0,0.99,13,11,17,21,120,130,169,199,10,20,20,19,2014-06-29,2014-07-27,2014-08-29,2014-09-30,10,10,10,10,NaT,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,331,0.0,0.0,0.0,0.0
71196,71197,144.709,100.963,15.810,0.00,156.39,192.33,3.21,0.00,6.01,6.31,0.00,0.00,5.16,0.0,1.13,2.1,10.26,0.0,3.68,0.0,0.0,5.79,0.00,0.00,0.78,2.23,0.00,0.00,0.15,1.63,0.0,0.00,1.28,0.00,0.0,0.00,0.93,9.66,0.00,0.00,146.13,186.53,0.00,0.00,3.79,2.45,0.00,0.00,0.0,0.0,0.0,0.0,149.93,188.98,0.00,0.00,0.0,0.0,0.0,0.0,1.28,0.76,0.76,0.00,0.00,0.0,0.0,0.0,152.14,199.41,0.76,0.00,3.91,13.34,2.86,0.00,0.26,6.96,0.00,0.00,2.86,8.51,0.68,0.00,7.04,28.83,3.54,0.00,0.00,0.20,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.00,0.0,0.00,0.20,0.00,0.00,7.59,29.03,3.54,0.00,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.55,0.00,0.0,0.00,9,11,4,2,147,94,15,0,36,20,15,0,2014-06-30,2014-07-19,2014-08-28,2014-09-19,7,7,0,0,NaT,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,489,0.0,0.0,0.0,0.0

## 2.4 Separate Categorical columns

Check if this dataset has any category columns. This may be determined by identifying which columns contain the numbers 1 and 0. These values are equivalent to yes and no, respectively.

In [14]:
cat_cols = []

for i in df.columns:
    if df[i].nunique()==2:
        cat_cols.append(i)
cat_cols

['night_pck_user_6',
 'night_pck_user_7',
 'night_pck_user_8',
 'night_pck_user_9',
 'fb_user_6',
 'fb_user_7',
 'fb_user_8',
 'fb_user_9']

## 2.5 Some Important Insights

### 2.5.1 Avaerage Revenue of call per user

In [15]:
arpu=[]
arpu_col= [col for col in df.columns if 'arpu' in col]

for i in df[arpu_col]:
    x=df[[i]].min()
    arpu.append(x)
print(arpu)

[arpu_6   -2258.709
dtype: float64, arpu_7   -2014.045
dtype: float64, arpu_8   -945.808
dtype: float64, arpu_9   -1899.505
dtype: float64, arpu_3g_6   -30.82
dtype: float64, arpu_3g_7   -26.04
dtype: float64, arpu_3g_8   -24.49
dtype: float64, arpu_3g_9   -71.09
dtype: float64, arpu_2g_6   -35.83
dtype: float64, arpu_2g_7   -15.48
dtype: float64, arpu_2g_8   -55.83
dtype: float64, arpu_2g_9   -45.74
dtype: float64]

`Observation`
The minimum values in arpu 6, arpu 7, arpu 8, and arpu 9 are seen to be negative. This suggests that certain clients are causing a loss for the business. I will maintain them in my study since my research criteria for a high-value client are based on usage-based churn, not revenue-based churn. Getting rid of them might result in the loss of some insightful knowledge. Observe their significance in the exploratory data analysis section before making a decision.

### 2.5.2 Sachet recharge
Recharge sachets are Service plans having a duration of less than one month. This indicates that the number of days needed to recharge a sachet should be fewer than 30. Any service plans that extend beyond 29 days should indicate that the client has performed a monthly recharge or that the entry is incorrect. Let us limit the values beyond 29 days to the maximum number of days recharged below 30 days.

In [16]:
sachet=[]
sachet_col= [col for col in df.columns if 'sachet' in col]

for i in df[sachet_col]:
    x=df[[i]].max()
    sachet.append(x)
print(sachet)

[sachet_2g_6    42
dtype: int64, sachet_2g_7    48
dtype: int64, sachet_2g_8    44
dtype: int64, sachet_2g_9    40
dtype: int64, sachet_3g_6    29
dtype: int64, sachet_3g_7    35
dtype: int64, sachet_3g_8    41
dtype: int64, sachet_3g_9    49
dtype: int64]

In [17]:
df['sachet_2g_6'] = df['sachet_2g_6'].clip(0,28)
df['sachet_2g_7'] = df['sachet_2g_7'].clip(0,29)
df['sachet_2g_8'] = df['sachet_2g_8'].clip(0,29)
df['sachet_3g_6'] = df['sachet_3g_6'].clip(0,29)
df['sachet_3g_7'] = df['sachet_3g_7'].clip(0,24)
df['sachet_3g_8'] = df['sachet_3g_8'].clip(0,29)

In [18]:
df.info(verbose=1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99999 entries, 0 to 99998
Data columns (total 210 columns):
 #    Column                    Dtype
---   ------                    -----
 0    cust_id                   int64
 1    arpu_6                    float64
 2    arpu_7                    float64
 3    arpu_8                    float64
 4    arpu_9                    float64
 5    onnet_mou_6               float64
 6    onnet_mou_7               float64
 7    onnet_mou_8               float64
 8    onnet_mou_9               float64
 9    offnet_mou_6              float64
 10   offnet_mou_7              float64
 11   offnet_mou_8              float64
 12   offnet_mou_9              float64
 13   roam_ic_mou_6             float64
 14   roam_ic_mou_7             float64
 15   roam_ic_mou_8             float64
 16   roam_ic_mou_9             float64
 17   roam_og_mou_6             float64
 18   roam_og_mou_7             float64
 19   roam_og_mou_8             float64
 20   roam_og_mou_9             float64
 21   loc_og_t2t_mou_6          float64
 22   loc_og_t2t_mou_7          float64
 23   loc_og_t2t_mou_8          float64
 24   loc_og_t2t_mou_9          float64
 25   loc_og_t2m_mou_6          float64
 26   loc_og_t2m_mou_7          float64
 27   loc_og_t2m_mou_8          float64
 28   loc_og_t2m_mou_9          float64
 29   loc_og_t2f_mou_6          float64
 30   loc_og_t2f_mou_7          float64
 31   loc_og_t2f_mou_8          float64
 32   loc_og_t2f_mou_9          float64
 33   loc_og_t2c_mou_6          float64
 34   loc_og_t2c_mou_7          float64
 35   loc_og_t2c_mou_8          float64
 36   loc_og_t2c_mou_9          float64
 37   loc_og_mou_6              float64
 38   loc_og_mou_7              float64
 39   loc_og_mou_8              float64
 40   loc_og_mou_9              float64
 41   std_og_t2t_mou_6          float64
 42   std_og_t2t_mou_7          float64
 43   std_og_t2t_mou_8          float64
 44   std_og_t2t_mou_9          float64
 45   std_og_t2m_mou_6          float64
 46   std_og_t2m_mou_7          float64
 47   std_og_t2m_mou_8          float64
 48   std_og_t2m_mou_9          float64
 49   std_og_t2f_mou_6          float64
 50   std_og_t2f_mou_7          float64
 51   std_og_t2f_mou_8          float64
 52   std_og_t2f_mou_9          float64
 53   std_og_mou_6              float64
 54   std_og_mou_7              float64
 55   std_og_mou_8              float64
 56   std_og_mou_9              float64
 57   isd_og_mou_6              float64
 58   isd_og_mou_7              float64
 59   isd_og_mou_8              float64
 60   isd_og_mou_9              float64
 61   spl_og_mou_6              float64
 62   spl_og_mou_7              float64
 63   spl_og_mou_8              float64
 64   spl_og_mou_9              float64
 65   og_others_6               float64
 66   og_others_7               float64
 67   og_others_8               float64
 68   og_others_9               float64
 69   total_og_mou_6            float64
 70   total_og_mou_7            float64
 71   total_og_mou_8            float64
 72   total_og_mou_9            float64
 73   loc_ic_t2t_mou_6          float64
 74   loc_ic_t2t_mou_7          float64
 75   loc_ic_t2t_mou_8          float64
 76   loc_ic_t2t_mou_9          float64
 77   loc_ic_t2m_mou_6          float64
 78   loc_ic_t2m_mou_7          float64
 79   loc_ic_t2m_mou_8          float64
 80   loc_ic_t2m_mou_9          float64
 81   loc_ic_t2f_mou_6          float64
 82   loc_ic_t2f_mou_7          float64
 83   loc_ic_t2f_mou_8          float64
 84   loc_ic_t2f_mou_9          float64
 85   loc_ic_mou_6              float64
 86   loc_ic_mou_7              float64
 87   loc_ic_mou_8              float64
 88   loc_ic_mou_9              float64
 89   std_ic_t2t_mou_6          float64
 90   std_ic_t2t_mou_7          float64
 91   std_ic_t2t_mou_8          float64
 92   std_ic_t2t_mou_9          float64
 93   std_ic_t2m_mou_6          float64
 94   std_ic_t2m_mou_7          float64
 95   std_ic_t2m_mou_8          float64
 96   std_ic_t2m_mou_9          float64
 97   std_ic_t2f_mou_6          float64
 98   std_ic_t2f_mou_7          float64
 99   std_ic_t2f_mou_8          float64
 100  std_ic_t2f_mou_9          float64
 101  std_ic_mou_6              float64
 102  std_ic_mou_7              float64
 103  std_ic_mou_8              float64
 104  std_ic_mou_9              float64
 105  total_ic_mou_6            float64
 106  total_ic_mou_7            float64
 107  total_ic_mou_8            float64
 108  total_ic_mou_9            float64
 109  spl_ic_mou_6              float64
 110  spl_ic_mou_7              float64
 111  spl_ic_mou_8              float64
 112  spl_ic_mou_9              float64
 113  isd_ic_mou_6              float64
 114  isd_ic_mou_7              float64
 115  isd_ic_mou_8              float64
 116  isd_ic_mou_9              float64
 117  ic_others_6               float64
 118  ic_others_7               float64
 119  ic_others_8               float64
 120  ic_others_9               float64
 121  total_rech_num_6          int64
 122  total_rech_num_7          int64
 123  total_rech_num_8          int64
 124  total_rech_num_9          int64
 125  total_rech_amt_6          int64
 126  total_rech_amt_7          int64
 127  total_rech_amt_8          int64
 128  total_rech_amt_9          int64
 129  max_rech_amt_6            int64
 130  max_rech_amt_7            int64
 131  max_rech_amt_8            int64
 132  max_rech_amt_9            int64
 133  date_of_last_rech_6       datetime64[ns]
 134  date_of_last_rech_7       datetime64[ns]
 135  date_of_last_rech_8       datetime64[ns]
 136  date_of_last_rech_9       datetime64[ns]
 137  last_day_rch_amt_6        int64
 138  last_day_rch_amt_7        int64
 139  last_day_rch_amt_8        int64
 140  last_day_rch_amt_9        int64
 141  date_of_last_rech_data_6  datetime64[ns]
 142  date_of_last_rech_data_7  datetime64[ns]
 143  date_of_last_rech_data_8  datetime64[ns]
 144  date_of_last_rech_data_9  datetime64[ns]
 145  total_rech_data_6         float64
 146  total_rech_data_7         float64
 147  total_rech_data_8         float64
 148  total_rech_data_9         float64
 149  max_rech_data_6           float64
 150  max_rech_data_7           float64
 151  max_rech_data_8           float64
 152  max_rech_data_9           float64
 153  count_rech_2g_6           float64
 154  count_rech_2g_7           float64
 155  count_rech_2g_8           float64
 156  count_rech_2g_9           float64
 157  count_rech_3g_6           float64
 158  count_rech_3g_7           float64
 159  count_rech_3g_8           float64
 160  count_rech_3g_9           float64
 161  av_rech_amt_data_6        float64
 162  av_rech_amt_data_7        float64
 163  av_rech_amt_data_8        float64
 164  av_rech_amt_data_9        float64
 165  vol_2g_mb_6               float64
 166  vol_2g_mb_7               float64
 167  vol_2g_mb_8               float64
 168  vol_2g_mb_9               float64
 169  vol_3g_mb_6               float64
 170  vol_3g_mb_7               float64
 171  vol_3g_mb_8               float64
 172  vol_3g_mb_9               float64
 173  arpu_3g_6                 float64
 174  arpu_3g_7                 float64
 175  arpu_3g_8                 float64
 176  arpu_3g_9                 float64
 177  arpu_2g_6                 float64
 178  arpu_2g_7                 float64
 179  arpu_2g_8                 float64
 180  arpu_2g_9                 float64
 181  night_pck_user_6          float64
 182  night_pck_user_7          float64
 183  night_pck_user_8          float64
 184  night_pck_user_9          float64
 185  monthly_2g_6              int64
 186  monthly_2g_7              int64
 187  monthly_2g_8              int64
 188  monthly_2g_9              int64
 189  sachet_2g_6               int64
 190  sachet_2g_7               int64
 191  sachet_2g_8               int64
 192  sachet_2g_9               int64
 193  monthly_3g_6              int64
 194  monthly_3g_7              int64
 195  monthly_3g_8              int64
 196  monthly_3g_9              int64
 197  sachet_3g_6               int64
 198  sachet_3g_7               int64
 199  sachet_3g_8               int64
 200  sachet_3g_9               int64
 201  fb_user_6                 float64
 202  fb_user_7                 float64
 203  fb_user_8                 float64
 204  fb_user_9                 float64
 205  aon                       int64
 206  vbc_3g_8                  float64
 207  vbc_3g_7                  float64
 208  vbc_3g_6                  float64
 209  vbc_3g_9                  float64
dtypes: datetime64[ns](8), float64(168), int64(34)
memory usage: 160.2 MB

# 3 Focusing on high value Customers

In [19]:
df['total_amt_6'] = df[['total_rech_amt_6', 'total_rech_data_6']].sum(axis=1)
df['total_amt_7'] = df[['total_rech_amt_7', 'total_rech_data_7']].sum(axis=1)
df['total_amt_8'] = df[['total_rech_amt_8', 'total_rech_data_8']].sum(axis=1)
df['total_amt_9'] = df[['total_rech_amt_9', 'total_rech_data_9']].sum(axis=1)

In [20]:
#calculate total recharge amount per user for months
df['total_rech_amt_per_user']=df[['total_amt_6','total_amt_7','total_amt_8','total_amt_9']].sum(axis=1)

In [21]:
df.sample(2)

,cust_id,arpu_6,arpu_7,arpu_8,arpu_9,onnet_mou_6,onnet_mou_7,onnet_mou_8,onnet_mou_9,offnet_mou_6,offnet_mou_7,offnet_mou_8,offnet_mou_9,roam_ic_mou_6,roam_ic_mou_7,roam_ic_mou_8,roam_ic_mou_9,roam_og_mou_6,roam_og_mou_7,roam_og_mou_8,roam_og_mou_9,loc_og_t2t_mou_6,loc_og_t2t_mou_7,loc_og_t2t_mou_8,loc_og_t2t_mou_9,loc_og_t2m_mou_6,loc_og_t2m_mou_7,loc_og_t2m_mou_8,loc_og_t2m_mou_9,loc_og_t2f_mou_6,loc_og_t2f_mou_7,loc_og_t2f_mou_8,loc_og_t2f_mou_9,loc_og_t2c_mou_6,loc_og_t2c_mou_7,loc_og_t2c_mou_8,loc_og_t2c_mou_9,loc_og_mou_6,loc_og_mou_7,loc_og_mou_8,loc_og_mou_9,std_og_t2t_mou_6,std_og_t2t_mou_7,std_og_t2t_mou_8,std_og_t2t_mou_9,std_og_t2m_mou_6,std_og_t2m_mou_7,std_og_t2m_mou_8,std_og_t2m_mou_9,std_og_t2f_mou_6,std_og_t2f_mou_7,std_og_t2f_mou_8,std_og_t2f_mou_9,std_og_mou_6,std_og_mou_7,std_og_mou_8,std_og_mou_9,isd_og_mou_6,isd_og_mou_7,isd_og_mou_8,isd_og_mou_9,spl_og_mou_6,spl_og_mou_7,spl_og_mou_8,spl_og_mou_9,og_others_6,og_others_7,og_others_8,og_others_9,total_og_mou_6,total_og_mou_7,total_og_mou_8,total_og_mou_9,loc_ic_t2t_mou_6,loc_ic_t2t_mou_7,loc_ic_t2t_mou_8,loc_ic_t2t_mou_9,loc_ic_t2m_mou_6,loc_ic_t2m_mou_7,loc_ic_t2m_mou_8,loc_ic_t2m_mou_9,loc_ic_t2f_mou_6,loc_ic_t2f_mou_7,loc_ic_t2f_mou_8,loc_ic_t2f_mou_9,loc_ic_mou_6,loc_ic_mou_7,loc_ic_mou_8,loc_ic_mou_9,std_ic_t2t_mou_6,std_ic_t2t_mou_7,std_ic_t2t_mou_8,std_ic_t2t_mou_9,std_ic_t2m_mou_6,std_ic_t2m_mou_7,std_ic_t2m_mou_8,std_ic_t2m_mou_9,std_ic_t2f_mou_6,std_ic_t2f_mou_7,std_ic_t2f_mou_8,std_ic_t2f_mou_9,std_ic_mou_6,std_ic_mou_7,std_ic_mou_8,std_ic_mou_9,total_ic_mou_6,total_ic_mou_7,total_ic_mou_8,total_ic_mou_9,spl_ic_mou_6,spl_ic_mou_7,spl_ic_mou_8,spl_ic_mou_9,isd_ic_mou_6,isd_ic_mou_7,isd_ic_mou_8,isd_ic_mou_9,ic_others_6,ic_others_7,ic_others_8,ic_others_9,total_rech_num_6,total_rech_num_7,total_rech_num_8,total_rech_num_9,total_rech_amt_6,total_rech_amt_7,total_rech_amt_8,total_rech_amt_9,max_rech_amt_6,max_rech_amt_7,max_rech_amt_8,max_rech_amt_9,date_of_last_rech_6,date_of_last_rech_7,date_of_last_rech_8,date_of_last_rech_9,last_day_rch_amt_6,last_day_rch_amt_7,last_day_rch_amt_8,last_day_rch_amt_9,date_of_last_rech_data_6,date_of_last_rech_data_7,date_of_last_rech_data_8,date_of_last_rech_data_9,total_rech_data_6,total_rech_data_7,total_rech_data_8,total_rech_data_9,max_rech_data_6,max_rech_data_7,max_rech_data_8,max_rech_data_9,count_rech_2g_6,count_rech_2g_7,count_rech_2g_8,count_rech_2g_9,count_rech_3g_6,count_rech_3g_7,count_rech_3g_8,count_rech_3g_9,av_rech_amt_data_6,av_rech_amt_data_7,av_rech_amt_data_8,av_rech_amt_data_9,vol_2g_mb_6,vol_2g_mb_7,vol_2g_mb_8,vol_2g_mb_9,vol_3g_mb_6,vol_3g_mb_7,vol_3g_mb_8,vol_3g_mb_9,arpu_3g_6,arpu_3g_7,arpu_3g_8,arpu_3g_9,arpu_2g_6,arpu_2g_7,arpu_2g_8,arpu_2g_9,night_pck_user_6,night_pck_user_7,night_pck_user_8,night_pck_user_9,monthly_2g_6,monthly_2g_7,monthly_2g_8,monthly_2g_9,sachet_2g_6,sachet_2g_7,sachet_2g_8,sachet_2g_9,monthly_3g_6,monthly_3g_7,monthly_3g_8,monthly_3g_9,sachet_3g_6,sachet_3g_7,sachet_3g_8,sachet_3g_9,fb_user_6,fb_user_7,fb_user_8,fb_user_9,aon,vbc_3g_8,vbc_3g_7,vbc_3g_6,vbc_3g_9,total_amt_6,total_amt_7,total_amt_8,total_amt_9,total_rech_amt_per_user
8594,8595,87.837,87.300,751.817,256.749,0.00,13.48,0.00,0.41,38.16,78.23,1.38,18.19,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.00,13.48,0.00,0.41,7.71,34.94,1.38,5.64,0.0,0.0,0.00,0.0,0.00,0.00,0.0,0.0,7.71,48.43,1.38,6.06,0.00,0.00,0.00,0.00,28.64,31.66,0.00,12.54,0.0,0.0,0.0,0.0,28.64,31.66,0.00,12.54,0.0,0.0,0.0,0.0,1.80,11.61,0.00,0.00,0.00,0.0,0.0,0.0,38.16,91.71,1.38,18.61,0.00,2.29,6.36,6.43,14.78,24.99,22.13,24.44,0.00,0.51,1.36,1.21,14.78,27.81,29.86,32.09,1.58,12.26,0.00,0.0,23.09,21.63,7.03,13.86,1.29,0.38,1.56,0.38,25.98,34.28,8.59,14.24,40.76,62.16,38.58,46.51,0.0,0.06,0.11,0.16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3,1,8,5,158,0,884,325,110,0,252,252,2014-06-22,2014-07-09,2014-08-24,2014-09-30,110,0,0,23,NaT,NaT,2014-08-20,2014-09-13,NaN,NaN,4.0,1.0,NaN,NaN,252.0,252.0,NaN,NaN,1.0,0.0,NaN,NaN,3.0,1.0,NaN,NaN,854.0,252.0,0.0,0.0,53.51,81.91,0.0,0.0,2215.43,1941.89,NaN,NaN,445.6,222.44,NaN,NaN,424.34,212.17,NaN,NaN,0.0,0.0,0,0,0,0,0,0,1,0,0,0,3,1,0,0,0,0,NaN,NaN,1.0,1.0,541,1474.7,0.0,0.0,68.84,158.0,0.0,888.0,326.0,1372.0
98308,98309,199.809,387.321,304.869,97.177,152.81,480.09,405.61,80.43,245.01,297.01,223.71,75.08,0.7,0.0,0.0,0.0,0.65,0.0,0.0,0.0,3.74,24.74,14.96,1.16,26.43,26.74,15.33,6.64,0.0,1.7,3.18,0.0,0.89,5.08,0.0,0.0,30.18,53.19,33.48,7.81,148.41,455.34,390.64,79.26,201.08,251.83,195.81,54.34,0.0,0.0,0.0,0.0,349.49,707.18,586.46,133.61,0.0,0.0,0.0,0.0,19.09,18.03,10.24,14.48,4.81,0.0,0.0,0.0,403.59,778.41,630.19,155.91,4.06,31.13,8.34,1.26,25.28,8.89,20.58,28.39,18.46,5.64,1.03,4.38,47.81,45.68,29.96,34.04,1.28,8.49,17.81,0.0,17.63,24.03,20.14,0.00,0.00,0.00,0.00,0.00,18.91,32.53,37.96,0.00,66.73,78.21,67.93,34.04,0.0,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8,7,8,3,246,544,346,19,110,128,130,19,2014-06-22,2014-07-29,2014-08-30,2014-09-21,50,128,0,0,NaT,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.00,0.00,0.0,0.0,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,336,0.0,0.0,0.0,0.00,246.0,544.0,346.0,19.0,1155.0

## 3.1 Filtering high value customers

In [22]:
avg_amt_rech=df['total_rech_amt_per_user'].mean()

In [24]:
high_val_customer = df.loc[df['total_rech_amt_per_user'] >= avg_amt_rech]
high_val_customer.head()

,cust_id,arpu_6,arpu_7,arpu_8,arpu_9,onnet_mou_6,onnet_mou_7,onnet_mou_8,onnet_mou_9,offnet_mou_6,offnet_mou_7,offnet_mou_8,offnet_mou_9,roam_ic_mou_6,roam_ic_mou_7,roam_ic_mou_8,roam_ic_mou_9,roam_og_mou_6,roam_og_mou_7,roam_og_mou_8,roam_og_mou_9,loc_og_t2t_mou_6,loc_og_t2t_mou_7,loc_og_t2t_mou_8,loc_og_t2t_mou_9,loc_og_t2m_mou_6,loc_og_t2m_mou_7,loc_og_t2m_mou_8,loc_og_t2m_mou_9,loc_og_t2f_mou_6,loc_og_t2f_mou_7,loc_og_t2f_mou_8,loc_og_t2f_mou_9,loc_og_t2c_mou_6,loc_og_t2c_mou_7,loc_og_t2c_mou_8,loc_og_t2c_mou_9,loc_og_mou_6,loc_og_mou_7,loc_og_mou_8,loc_og_mou_9,std_og_t2t_mou_6,std_og_t2t_mou_7,std_og_t2t_mou_8,std_og_t2t_mou_9,std_og_t2m_mou_6,std_og_t2m_mou_7,std_og_t2m_mou_8,std_og_t2m_mou_9,std_og_t2f_mou_6,std_og_t2f_mou_7,std_og_t2f_mou_8,std_og_t2f_mou_9,std_og_mou_6,std_og_mou_7,std_og_mou_8,std_og_mou_9,isd_og_mou_6,isd_og_mou_7,isd_og_mou_8,isd_og_mou_9,spl_og_mou_6,spl_og_mou_7,spl_og_mou_8,spl_og_mou_9,og_others_6,og_others_7,og_others_8,og_others_9,total_og_mou_6,total_og_mou_7,total_og_mou_8,total_og_mou_9,loc_ic_t2t_mou_6,loc_ic_t2t_mou_7,loc_ic_t2t_mou_8,loc_ic_t2t_mou_9,loc_ic_t2m_mou_6,loc_ic_t2m_mou_7,loc_ic_t2m_mou_8,loc_ic_t2m_mou_9,loc_ic_t2f_mou_6,loc_ic_t2f_mou_7,loc_ic_t2f_mou_8,loc_ic_t2f_mou_9,loc_ic_mou_6,loc_ic_mou_7,loc_ic_mou_8,loc_ic_mou_9,std_ic_t2t_mou_6,std_ic_t2t_mou_7,std_ic_t2t_mou_8,std_ic_t2t_mou_9,std_ic_t2m_mou_6,std_ic_t2m_mou_7,std_ic_t2m_mou_8,std_ic_t2m_mou_9,std_ic_t2f_mou_6,std_ic_t2f_mou_7,std_ic_t2f_mou_8,std_ic_t2f_mou_9,std_ic_mou_6,std_ic_mou_7,std_ic_mou_8,std_ic_mou_9,total_ic_mou_6,total_ic_mou_7,total_ic_mou_8,total_ic_mou_9,spl_ic_mou_6,spl_ic_mou_7,spl_ic_mou_8,spl_ic_mou_9,isd_ic_mou_6,isd_ic_mou_7,isd_ic_mou_8,isd_ic_mou_9,ic_others_6,ic_others_7,ic_others_8,ic_others_9,total_rech_num_6,total_rech_num_7,total_rech_num_8,total_rech_num_9,total_rech_amt_6,total_rech_amt_7,total_rech_amt_8,total_rech_amt_9,max_rech_amt_6,max_rech_amt_7,max_rech_amt_8,max_rech_amt_9,date_of_last_rech_6,date_of_last_rech_7,date_of_last_rech_8,date_of_last_rech_9,last_day_rch_amt_6,last_day_rch_amt_7,last_day_rch_amt_8,last_day_rch_amt_9,date_of_last_rech_data_6,date_of_last_rech_data_7,date_of_last_rech_data_8,date_of_last_rech_data_9,total_rech_data_6,total_rech_data_7,total_rech_data_8,total_rech_data_9,max_rech_data_6,max_rech_data_7,max_rech_data_8,max_rech_data_9,count_rech_2g_6,count_rech_2g_7,count_rech_2g_8,count_rech_2g_9,count_rech_3g_6,count_rech_3g_7,count_rech_3g_8,count_rech_3g_9,av_rech_amt_data_6,av_rech_amt_data_7,av_rech_amt_data_8,av_rech_amt_data_9,vol_2g_mb_6,vol_2g_mb_7,vol_2g_mb_8,vol_2g_mb_9,vol_3g_mb_6,vol_3g_mb_7,vol_3g_mb_8,vol_3g_mb_9,arpu_3g_6,arpu_3g_7,arpu_3g_8,arpu_3g_9,arpu_2g_6,arpu_2g_7,arpu_2g_8,arpu_2g_9,night_pck_user_6,night_pck_user_7,night_pck_user_8,night_pck_user_9,monthly_2g_6,monthly_2g_7,monthly_2g_8,monthly_2g_9,sachet_2g_6,sachet_2g_7,sachet_2g_8,sachet_2g_9,monthly_3g_6,monthly_3g_7,monthly_3g_8,monthly_3g_9,sachet_3g_6,sachet_3g_7,sachet_3g_8,sachet_3g_9,fb_user_6,fb_user_7,fb_user_8,fb_user_9,aon,vbc_3g_8,vbc_3g_7,vbc_3g_6,vbc_3g_9,total_amt_6,total_amt_7,total_amt_8,total_amt_9,total_rech_amt_per_user
3,4,221.338,251.102,508.054,389.500,99.91,54.39,310.98,241.71,123.31,109.01,71.68,113.54,0.00,54.86,44.38,0.00,0.00,28.09,39.04,0.00,73.68,34.81,10.61,15.49,107.43,83.21,22.46,65.46,1.91,0.65,4.91,2.06,0.0,0.00,0.00,0.00,183.03,118.68,37.99,83.03,26.23,14.89,289.58,226.21,2.99,1.73,6.53,9.99,0.00,0.00,0.00,0.0,29.23,16.63,296.11,236.21,0.0,0.00,0.00,0.0,10.96,0.00,18.09,43.29,0.0,0.0,0.0,0.0,223.23,135.31,352.21,362.54,62.08,19.98,8.04,41.73,113.96,64.51,20.28,52.86,57.43,27.09,19.84,65.59,233.48,111.59,48.18,160.19,43.48,66.44,0.00,129.84,1.33,38.56,4.94,13.98,1.18,0.00,0.00,0.0,45.99,105.01,4.94,143.83,280.08,216.61,53.13,305.38,0.59,0.0,0.00,0.55,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.80,10,11,18,14,230,310,601,410,60,50,50,50,2014-06-28,2014-07-31,2014-08-31,2014-09-30,30,50,50,30,NaT,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,2491,0.00,0.00,0.00,0.0,230.0,310.0,601.0,410.0,1551.0
7,8,1069.180,1349.850,3171.480,500.000,57.84,54.68,52.29,NaN,453.43,567.16,325.91,NaN,16.23,33.49,31.64,NaN,23.74,12.59,38.06,NaN,51.39,31.38,40.28,NaN,308.63,447.38,162.28,NaN,62.13,55.14,53.23,NaN,0.0,0.00,0.00,NaN,422.16,533.91,255.79,NaN,4.30,23.29,12.01,NaN,49.89,31.76,49.14,NaN,6.66,20.08,16.68,NaN,60.86,75.14,77.84,NaN,0.0,0.18,10.01,NaN,4.50,0.00,6.50,NaN,0.0,0.0,0.0,NaN,487.53,609.24,350.16,0.00,58.14,32.26,27.31,NaN,217.56,221.49,121.19,NaN,152.16,101.46,39.53,NaN,427.88,355.23,188.04,NaN,36.89,11.83,30.39,NaN,91.44,126.99,141.33,NaN,52.19,34.24,22.21,NaN,180.54,173.08,193.94,NaN,626.46,558.04,428.74,0.00,0.21,0.0,0.00,NaN,2.06,14.53,31.59,NaN,15.74,15.19,15.14,NaN,5,5,7,3,1580,790,3638,0,1580,790,1580,0,2014-06-27,2014-07-25,2014-08-26,2014-09-30,0,0,779,0,NaT,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,802,57.74,19.38,18.74,0.0,1580.0,790.0,3638.0,0.0,6008.0
8,9,378.721,492.223,137.362,166.787,413.69,351.03,35.08,33.46,94.66,80.63,136.48,108.71,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,297.13,217.59,12.49,26.13,80.96,70.58,50.54,34.58,0.00,0.00,0.00,0.00,0.0,0.00,7.15,0.00,378.09,288.18,63.04,60.71,116.56,133.43,22.58,7.33,13.69,10.04,75.69,74.13,0.00,0.00,0.00,0.0,130.26,143.48,98.28,81.46,0.0,0.00,0.00,0.0,0.00,0.00,10.23,0.00,0.0,0.0,0.0,0.0,508.36,431.66,171.56,142.18,23.84,9.84,0.31,4.03,57.58,13.98,15.48,17.34,0.00,0.00,0.00,0.00,81.43,23.83,15.79,21.38,0.00,0.58,0.10,0.00,22.43,4.08,0.65,13.53,0.00,0.00,0.00,0.0,22.43,4.66,0.75,13.53,103.86,28.49,16.54,34.91,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,19,21,14,15,437,601,120,186,90,154,30,36,2014-06-25,2014-07-31,2014-08-30,2014-09-30,50,0,10,0,NaT,2014-07-31,2014-08-23,NaT,NaN,2.0,3.0,NaN,NaN,154.0,23.0,NaN,NaN,2.0,3.0,NaN,NaN,0.0,0.0,NaN,NaN,177.0,69.0,NaN,0.0,356.0,0.03,0.0,0.0,750.95,11.94,0.0,NaN,0.0,19.83,NaN,NaN,0.0,0.0,NaN,NaN,0.0,0.0,NaN,0,1,0,0,0,1,3,0,0,0,0,0,0,0,0,0,NaN,1.0,1.0,NaN,315,21.03,910.65,122.16,0.0,437.0,603.0,123.0,186.0,1349.0
13,14,492.846,205.671,593.260,322.732,501.76,108.39,534.24,244.81,413.31,119.28,482.46,214.06,23.53,144.24,72.11,136.78,7.98,35.26,1.44,12.78,49.63,6.19,36.01,6.14,151.13,47.28,294.46,108.24,4.54,0.00,23.51,5.29,0.0,0.00,0.49,0.00,205.31,53.48,353.99,119.69,446.41,85.98,498.23,230.38,255.36,52.94,156.94,96.01,0.00,0.00,0.00,0.0,701.78,138.93,655.18,326.39,0.0,0.00,1.29,0.0,0.00,0.00,4.78,0.00,0.0,0.0,0.0,0.0,907.09,192.41,1015.26,446.09,67.88,7.58,52.58,24.98,142.88,18.53,195.18,104.79,4.81,0.00,7.49,8.51,215.58,26.11,255.26,138.29,115.68,38.29,154.58,62.39,308.13,29.79,317.91,151.51,0.00,0.00,1.91,0.0,423.81,68.09,474.41,213.91,968.61,172.58,1144.53,631.86,0.45,0.0,0.00,0.00,245.28,62.11,393.39,259.33,83.48,16.24,21.44,20.31,6,4,11,7,507,253,717,353,110,110,130,130,2014-06-20,2014-07-22,2014-08-30,2014-09-26,110,50,0,0,NaT,NaT,2014-08-30,NaT,NaN,NaN,3.0,NaN,NaN,NaN,23.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,0.0,NaN,NaN,NaN,69.0,NaN,0.0,0.0,0.02,0.0,0.0,0.00,0.00,0.0,NaN,NaN,0.00,NaN,NaN,NaN,0.2,NaN,NaN,NaN,0.0,NaN,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,NaN,NaN,1.0,NaN,2607,0.00,0.00,0.00,0.0,507.0,253.0,720.0,353.0,1833.0
15,16,31.000,510.465,590.643,510.390,NaN,246.56,280.31,289.79,NaN,839.58,1011.91,642.14,NaN,0.00,0.00,0.00,NaN,0.88,0.00,0.00,NaN,16.13,44.79,48.33,NaN,38.99,92.53,158.11,NaN,5.13,4.83,8.43,NaN,9.78,0.00,0.03,NaN,60.26,142.16,214.88,NaN,230.43,235.51,241.46,NaN,775.66,914.54,475.56,NaN,0.00,0.00,0.0,NaN,1006.09,1150.06,717.03,NaN,0.00,0.00,0.0,NaN,18.89,0.00,0.03,NaN,0.0,0.0,0.0,0.00,1085.26,1292.23,931.94,NaN,16.91,16.19,14.91,NaN,36.94,45.76,50.01,NaN,7.24,9.51,15.54,NaN,61.11,71.48,80.48,NaN,1.76,2.68,30.16,NaN,40.06,14.31,82.46,NaN,0.00,0.00,0.0,NaN,41.83,16.99,112.63,0.00,105.86,89.71,198.28,NaN,0.0,0.61,1.01,NaN,0.00,0.00,0.00,NaN,2.91,0.61,4.14,1,13,11,8,0,686,696,556,0,110,130,130,2014-06-14,2014-07-28,2014-08-30,2014-09-29,0,110,130,0,NaT,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,270,0.00,0.00,0.00,0.0,0.0,686.0,696.0,556.0,1938.0

In [27]:
print("Total number of high value customers: ",len(high_val_customer))

Total number of high value customers:  34958

# 4 Creating Target Variable¶

In this step, I will tag the churned customers whose target variable is categorised as churn Yes or churn No (Yes=1, No=0) based on T-four-month Mobile's data.

## 4.1 Find put inactive customers

During the churn period, those who have not made any calls (incoming or outgoing) and have not utilized mobile internet even once are considered to be inactive. The following attributes must be used to identify churners:

* total_ic_mou_6
* total_ic_mou_7
* total_ic_mou_8
* total_ic_mou_9
* total_og_mou_6
* total_og_mou_7
* total_og_mou_8
* total_og_mou_9
* vol_2g_mb_6
* vol_2g_mb_7
* vol_2g_mb_8
* vol_2g_mb_9
* vol_3g_mb_6
* vol_3g_mb_7
* vol_3g_mb_8
* vol_3g_mb_9

In [28]:
# The month of September is used to screen out churned customers.

df['churn'] = df.apply(lambda x: 1 if (x.total_ic_mou_9 == 0 and x.total_og_mou_9 == 0 and x.vol_2g_mb_9 ==0 and x.vol_3g_mb_9==0) else 0, axis=1)
df['churn'] = df['churn'].astype("str")
df.shape

(99999, 216)

In [29]:
# number of churned customers
df['churn'].value_counts()

0    89808
1    10191
Name: churn, dtype: int64

In [37]:
#what's the % of churned customers
print("The Percentage of churned customers is:" , round(100*(df.churn.astype("int").sum()/len(df)),2))

The Percentage of churned customers is: 10.19

### 4.2 After labeling churners, let's delete any characteristics pertaining to the churn phase (those with' 9', etc. in their names).

In [38]:
col_9 = [i for i in df.columns if '9' in i]
df = df.drop(col_9,axis=1)
df.shape

(99999, 163)

In [39]:
# let's update our categorical column list
cat_cols = [ele for ele in cat_cols if ele not in col_9]
cat_cols

['night_pck_user_6',
 'night_pck_user_7',
 'night_pck_user_8',
 'fb_user_6',
 'fb_user_7',
 'fb_user_8']

In [40]:
df.info(verbose=1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99999 entries, 0 to 99998
Data columns (total 163 columns):
 #    Column                    Dtype
---   ------                    -----
 0    cust_id                   int64
 1    arpu_6                    float64
 2    arpu_7                    float64
 3    arpu_8                    float64
 4    onnet_mou_6               float64
 5    onnet_mou_7               float64
 6    onnet_mou_8               float64
 7    offnet_mou_6              float64
 8    offnet_mou_7              float64
 9    offnet_mou_8              float64
 10   roam_ic_mou_6             float64
 11   roam_ic_mou_7             float64
 12   roam_ic_mou_8             float64
 13   roam_og_mou_6             float64
 14   roam_og_mou_7             float64
 15   roam_og_mou_8             float64
 16   loc_og_t2t_mou_6          float64
 17   loc_og_t2t_mou_7          float64
 18   loc_og_t2t_mou_8          float64
 19   loc_og_t2m_mou_6          float64
 20   loc_og_t2m_mou_7          float64
 21   loc_og_t2m_mou_8          float64
 22   loc_og_t2f_mou_6          float64
 23   loc_og_t2f_mou_7          float64
 24   loc_og_t2f_mou_8          float64
 25   loc_og_t2c_mou_6          float64
 26   loc_og_t2c_mou_7          float64
 27   loc_og_t2c_mou_8          float64
 28   loc_og_mou_6              float64
 29   loc_og_mou_7              float64
 30   loc_og_mou_8              float64
 31   std_og_t2t_mou_6          float64
 32   std_og_t2t_mou_7          float64
 33   std_og_t2t_mou_8          float64
 34   std_og_t2m_mou_6          float64
 35   std_og_t2m_mou_7          float64
 36   std_og_t2m_mou_8          float64
 37   std_og_t2f_mou_6          float64
 38   std_og_t2f_mou_7          float64
 39   std_og_t2f_mou_8          float64
 40   std_og_mou_6              float64
 41   std_og_mou_7              float64
 42   std_og_mou_8              float64
 43   isd_og_mou_6              float64
 44   isd_og_mou_7              float64
 45   isd_og_mou_8              float64
 46   spl_og_mou_6              float64
 47   spl_og_mou_7              float64
 48   spl_og_mou_8              float64
 49   og_others_6               float64
 50   og_others_7               float64
 51   og_others_8               float64
 52   total_og_mou_6            float64
 53   total_og_mou_7            float64
 54   total_og_mou_8            float64
 55   loc_ic_t2t_mou_6          float64
 56   loc_ic_t2t_mou_7          float64
 57   loc_ic_t2t_mou_8          float64
 58   loc_ic_t2m_mou_6          float64
 59   loc_ic_t2m_mou_7          float64
 60   loc_ic_t2m_mou_8          float64
 61   loc_ic_t2f_mou_6          float64
 62   loc_ic_t2f_mou_7          float64
 63   loc_ic_t2f_mou_8          float64
 64   loc_ic_mou_6              float64
 65   loc_ic_mou_7              float64
 66   loc_ic_mou_8              float64
 67   std_ic_t2t_mou_6          float64
 68   std_ic_t2t_mou_7          float64
 69   std_ic_t2t_mou_8          float64
 70   std_ic_t2m_mou_6          float64
 71   std_ic_t2m_mou_7          float64
 72   std_ic_t2m_mou_8          float64
 73   std_ic_t2f_mou_6          float64
 74   std_ic_t2f_mou_7          float64
 75   std_ic_t2f_mou_8          float64
 76   std_ic_mou_6              float64
 77   std_ic_mou_7              float64
 78   std_ic_mou_8              float64
 79   total_ic_mou_6            float64
 80   total_ic_mou_7            float64
 81   total_ic_mou_8            float64
 82   spl_ic_mou_6              float64
 83   spl_ic_mou_7              float64
 84   spl_ic_mou_8              float64
 85   isd_ic_mou_6              float64
 86   isd_ic_mou_7              float64
 87   isd_ic_mou_8              float64
 88   ic_others_6               float64
 89   ic_others_7               float64
 90   ic_others_8               float64
 91   total_rech_num_6          int64
 92   total_rech_num_7          int64
 93   total_rech_num_8          int64
 94   total_rech_amt_6          int64
 95   total_rech_amt_7          int64
 96   total_rech_amt_8          int64
 97   max_rech_amt_6            int64
 98   max_rech_amt_7            int64
 99   max_rech_amt_8            int64
 100  date_of_last_rech_6       datetime64[ns]
 101  date_of_last_rech_7       datetime64[ns]
 102  date_of_last_rech_8       datetime64[ns]
 103  last_day_rch_amt_6        int64
 104  last_day_rch_amt_7        int64
 105  last_day_rch_amt_8        int64
 106  date_of_last_rech_data_6  datetime64[ns]
 107  date_of_last_rech_data_7  datetime64[ns]
 108  date_of_last_rech_data_8  datetime64[ns]
 109  total_rech_data_6         float64
 110  total_rech_data_7         float64
 111  total_rech_data_8         float64
 112  max_rech_data_6           float64
 113  max_rech_data_7           float64
 114  max_rech_data_8           float64
 115  count_rech_2g_6           float64
 116  count_rech_2g_7           float64
 117  count_rech_2g_8           float64
 118  count_rech_3g_6           float64
 119  count_rech_3g_7           float64
 120  count_rech_3g_8           float64
 121  av_rech_amt_data_6        float64
 122  av_rech_amt_data_7        float64
 123  av_rech_amt_data_8        float64
 124  vol_2g_mb_6               float64
 125  vol_2g_mb_7               float64
 126  vol_2g_mb_8               float64
 127  vol_3g_mb_6               float64
 128  vol_3g_mb_7               float64
 129  vol_3g_mb_8               float64
 130  arpu_3g_6                 float64
 131  arpu_3g_7                 float64
 132  arpu_3g_8                 float64
 133  arpu_2g_6                 float64
 134  arpu_2g_7                 float64
 135  arpu_2g_8                 float64
 136  night_pck_user_6          float64
 137  night_pck_user_7          float64
 138  night_pck_user_8          float64
 139  monthly_2g_6              int64
 140  monthly_2g_7              int64
 141  monthly_2g_8              int64
 142  sachet_2g_6               int64
 143  sachet_2g_7               int64
 144  sachet_2g_8               int64
 145  monthly_3g_6              int64
 146  monthly_3g_7              int64
 147  monthly_3g_8              int64
 148  sachet_3g_6               int64
 149  sachet_3g_7               int64
 150  sachet_3g_8               int64
 151  fb_user_6                 float64
 152  fb_user_7                 float64
 153  fb_user_8                 float64
 154  aon                       int64
 155  vbc_3g_8                  float64
 156  vbc_3g_7                  float64
 157  vbc_3g_6                  float64
 158  total_amt_6               float64
 159  total_amt_7               float64
 160  total_amt_8               float64
 161  total_rech_amt_per_user   float64
 162  churn                     object
dtypes: datetime64[ns](6), float64(130), int64(26), object(1)
memory usage: 124.4+ MB

In [41]:
df.sample(2)

,cust_id,arpu_6,arpu_7,arpu_8,onnet_mou_6,onnet_mou_7,onnet_mou_8,offnet_mou_6,offnet_mou_7,offnet_mou_8,roam_ic_mou_6,roam_ic_mou_7,roam_ic_mou_8,roam_og_mou_6,roam_og_mou_7,roam_og_mou_8,loc_og_t2t_mou_6,loc_og_t2t_mou_7,loc_og_t2t_mou_8,loc_og_t2m_mou_6,loc_og_t2m_mou_7,loc_og_t2m_mou_8,loc_og_t2f_mou_6,loc_og_t2f_mou_7,loc_og_t2f_mou_8,loc_og_t2c_mou_6,loc_og_t2c_mou_7,loc_og_t2c_mou_8,loc_og_mou_6,loc_og_mou_7,loc_og_mou_8,std_og_t2t_mou_6,std_og_t2t_mou_7,std_og_t2t_mou_8,std_og_t2m_mou_6,std_og_t2m_mou_7,std_og_t2m_mou_8,std_og_t2f_mou_6,std_og_t2f_mou_7,std_og_t2f_mou_8,std_og_mou_6,std_og_mou_7,std_og_mou_8,isd_og_mou_6,isd_og_mou_7,isd_og_mou_8,spl_og_mou_6,spl_og_mou_7,spl_og_mou_8,og_others_6,og_others_7,og_others_8,total_og_mou_6,total_og_mou_7,total_og_mou_8,loc_ic_t2t_mou_6,loc_ic_t2t_mou_7,loc_ic_t2t_mou_8,loc_ic_t2m_mou_6,loc_ic_t2m_mou_7,loc_ic_t2m_mou_8,loc_ic_t2f_mou_6,loc_ic_t2f_mou_7,loc_ic_t2f_mou_8,loc_ic_mou_6,loc_ic_mou_7,loc_ic_mou_8,std_ic_t2t_mou_6,std_ic_t2t_mou_7,std_ic_t2t_mou_8,std_ic_t2m_mou_6,std_ic_t2m_mou_7,std_ic_t2m_mou_8,std_ic_t2f_mou_6,std_ic_t2f_mou_7,std_ic_t2f_mou_8,std_ic_mou_6,std_ic_mou_7,std_ic_mou_8,total_ic_mou_6,total_ic_mou_7,total_ic_mou_8,spl_ic_mou_6,spl_ic_mou_7,spl_ic_mou_8,isd_ic_mou_6,isd_ic_mou_7,isd_ic_mou_8,ic_others_6,ic_others_7,ic_others_8,total_rech_num_6,total_rech_num_7,total_rech_num_8,total_rech_amt_6,total_rech_amt_7,total_rech_amt_8,max_rech_amt_6,max_rech_amt_7,max_rech_amt_8,date_of_last_rech_6,date_of_last_rech_7,date_of_last_rech_8,last_day_rch_amt_6,last_day_rch_amt_7,last_day_rch_amt_8,date_of_last_rech_data_6,date_of_last_rech_data_7,date_of_last_rech_data_8,total_rech_data_6,total_rech_data_7,total_rech_data_8,max_rech_data_6,max_rech_data_7,max_rech_data_8,count_rech_2g_6,count_rech_2g_7,count_rech_2g_8,count_rech_3g_6,count_rech_3g_7,count_rech_3g_8,av_rech_amt_data_6,av_rech_amt_data_7,av_rech_amt_data_8,vol_2g_mb_6,vol_2g_mb_7,vol_2g_mb_8,vol_3g_mb_6,vol_3g_mb_7,vol_3g_mb_8,arpu_3g_6,arpu_3g_7,arpu_3g_8,arpu_2g_6,arpu_2g_7,arpu_2g_8,night_pck_user_6,night_pck_user_7,night_pck_user_8,monthly_2g_6,monthly_2g_7,monthly_2g_8,sachet_2g_6,sachet_2g_7,sachet_2g_8,monthly_3g_6,monthly_3g_7,monthly_3g_8,sachet_3g_6,sachet_3g_7,sachet_3g_8,fb_user_6,fb_user_7,fb_user_8,aon,vbc_3g_8,vbc_3g_7,vbc_3g_6,total_amt_6,total_amt_7,total_amt_8,total_rech_amt_per_user,churn
71941,71942,72.822,129.473,112.505,4.04,9.64,1.15,41.59,71.13,65.39,0.0,0.0,0.0,0.0,0.0,0.0,1.81,5.49,0.00,33.84,55.96,63.14,0.36,0.0,0.6,0.0,0.0,0.0,36.03,61.46,63.74,2.23,4.15,1.15,7.38,14.99,1.65,0.0,0.0,0.0,9.61,19.14,2.80,0.0,0.16,0.0,0.00,0.00,0.0,0.0,0.0,0.0,45.64,80.78,66.54,0.79,5.21,0.85,42.51,72.01,77.89,2.76,5.93,15.89,46.08,83.16,94.64,0.00,0.00,0.00,0.00,0.00,1.20,0.0,0.0,0.0,0.00,0.00,1.20,46.08,83.16,95.84,0.0,0.0,0.0,0.00,0.00,0.00,0.00,0.0,0.0,2,5,4,100,195,230,50,65,130,2014-06-28,2014-07-30,2014-08-28,50,65,130,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,2204,0.0,0.0,0.0,100.0,195.0,230.0,525.0,0
16847,16848,506.170,401.173,299.656,628.58,630.88,405.99,365.44,156.06,179.58,0.0,0.0,0.0,0.0,0.0,0.0,4.13,3.11,1.81,19.99,25.54,57.33,0.00,0.0,0.0,0.0,0.0,0.0,24.13,28.66,59.14,624.44,627.76,404.18,345.44,130.51,122.24,0.0,0.0,0.0,969.89,758.28,526.43,0.0,0.00,0.0,4.81,1.68,0.0,0.0,0.0,0.0,998.84,788.63,585.58,66.88,40.33,0.11,54.73,170.13,130.66,0.00,0.00,0.00,121.61,210.46,130.78,24.29,12.39,18.28,16.79,2.89,15.28,0.0,0.0,0.0,41.09,15.29,33.56,205.39,242.71,189.79,0.0,0.0,0.0,42.23,16.94,25.45,0.44,0.0,0.0,15,12,11,566,437,480,90,50,130,2014-06-30,2014-07-29,2014-08-29,50,23,130,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,1084,0.0,0.0,0.0,566.0,437.0,480.0,2195.0,0

# 5 Developing new features

In [43]:
#AON: Age on network 
#Conevrt AON in years
df['aon_yr'] = round((df['aon']/365),1)

In [44]:
df.drop('aon', axis=1, inplace=True)
df.sample(2)

,cust_id,arpu_6,arpu_7,arpu_8,onnet_mou_6,onnet_mou_7,onnet_mou_8,offnet_mou_6,offnet_mou_7,offnet_mou_8,roam_ic_mou_6,roam_ic_mou_7,roam_ic_mou_8,roam_og_mou_6,roam_og_mou_7,roam_og_mou_8,loc_og_t2t_mou_6,loc_og_t2t_mou_7,loc_og_t2t_mou_8,loc_og_t2m_mou_6,loc_og_t2m_mou_7,loc_og_t2m_mou_8,loc_og_t2f_mou_6,loc_og_t2f_mou_7,loc_og_t2f_mou_8,loc_og_t2c_mou_6,loc_og_t2c_mou_7,loc_og_t2c_mou_8,loc_og_mou_6,loc_og_mou_7,loc_og_mou_8,std_og_t2t_mou_6,std_og_t2t_mou_7,std_og_t2t_mou_8,std_og_t2m_mou_6,std_og_t2m_mou_7,std_og_t2m_mou_8,std_og_t2f_mou_6,std_og_t2f_mou_7,std_og_t2f_mou_8,std_og_mou_6,std_og_mou_7,std_og_mou_8,isd_og_mou_6,isd_og_mou_7,isd_og_mou_8,spl_og_mou_6,spl_og_mou_7,spl_og_mou_8,og_others_6,og_others_7,og_others_8,total_og_mou_6,total_og_mou_7,total_og_mou_8,loc_ic_t2t_mou_6,loc_ic_t2t_mou_7,loc_ic_t2t_mou_8,loc_ic_t2m_mou_6,loc_ic_t2m_mou_7,loc_ic_t2m_mou_8,loc_ic_t2f_mou_6,loc_ic_t2f_mou_7,loc_ic_t2f_mou_8,loc_ic_mou_6,loc_ic_mou_7,loc_ic_mou_8,std_ic_t2t_mou_6,std_ic_t2t_mou_7,std_ic_t2t_mou_8,std_ic_t2m_mou_6,std_ic_t2m_mou_7,std_ic_t2m_mou_8,std_ic_t2f_mou_6,std_ic_t2f_mou_7,std_ic_t2f_mou_8,std_ic_mou_6,std_ic_mou_7,std_ic_mou_8,total_ic_mou_6,total_ic_mou_7,total_ic_mou_8,spl_ic_mou_6,spl_ic_mou_7,spl_ic_mou_8,isd_ic_mou_6,isd_ic_mou_7,isd_ic_mou_8,ic_others_6,ic_others_7,ic_others_8,total_rech_num_6,total_rech_num_7,total_rech_num_8,total_rech_amt_6,total_rech_amt_7,total_rech_amt_8,max_rech_amt_6,max_rech_amt_7,max_rech_amt_8,date_of_last_rech_6,date_of_last_rech_7,date_of_last_rech_8,last_day_rch_amt_6,last_day_rch_amt_7,last_day_rch_amt_8,date_of_last_rech_data_6,date_of_last_rech_data_7,date_of_last_rech_data_8,total_rech_data_6,total_rech_data_7,total_rech_data_8,max_rech_data_6,max_rech_data_7,max_rech_data_8,count_rech_2g_6,count_rech_2g_7,count_rech_2g_8,count_rech_3g_6,count_rech_3g_7,count_rech_3g_8,av_rech_amt_data_6,av_rech_amt_data_7,av_rech_amt_data_8,vol_2g_mb_6,vol_2g_mb_7,vol_2g_mb_8,vol_3g_mb_6,vol_3g_mb_7,vol_3g_mb_8,arpu_3g_6,arpu_3g_7,arpu_3g_8,arpu_2g_6,arpu_2g_7,arpu_2g_8,night_pck_user_6,night_pck_user_7,night_pck_user_8,monthly_2g_6,monthly_2g_7,monthly_2g_8,sachet_2g_6,sachet_2g_7,sachet_2g_8,monthly_3g_6,monthly_3g_7,monthly_3g_8,sachet_3g_6,sachet_3g_7,sachet_3g_8,fb_user_6,fb_user_7,fb_user_8,vbc_3g_8,vbc_3g_7,vbc_3g_6,total_amt_6,total_amt_7,total_amt_8,total_rech_amt_per_user,churn,aon_yr
95781,95782,665.509,601.760,532.533,835.94,748.04,728.21,321.19,277.54,296.64,0.0,0.0,0.0,0.0,0.0,0.0,134.98,81.04,108.83,306.83,238.29,276.43,4.36,3.5,11.54,0.0,0.0,0.0,446.18,322.84,396.81,700.96,666.99,619.38,5.98,35.74,8.66,0.0,0.0,0.0,706.94,702.74,628.04,4.01,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,1157.14,1025.59,1024.86,7.76,33.59,14.71,89.79,73.01,166.41,2.41,0.21,0.00,99.98,106.83,181.13,5.21,24.08,24.56,1.9,5.16,1.69,0.0,0.00,0.0,7.11,29.24,26.26,107.74,136.08,207.39,0.15,0.0,0.00,0.0,0.0,0.0,0.5,0.00,0.0,13,21,14,747,747,617,110,110,130,2014-06-29,2014-07-30,2014-08-31,30,0,0,2014-06-25,NaT,2014-08-24,1.0,NaN,1.0,25.0,NaN,25.0,1.0,NaN,1.0,0.0,NaN,0.0,25.0,NaN,25.0,0.0,0.0,0.0,0.0,0.0,0.02,0.0,NaN,1.32,0.0,NaN,0.0,0.0,NaN,0.0,0,0,0,1,0,1,0,0,0,0,0,0,0.0,NaN,1.0,0.0,0.0,0.0,748.0,747.0,618.0,2820.0,0,2.0
11744,11745,57.134,70.838,78.482,30.84,15.71,22.13,25.36,49.26,49.43,0.0,0.0,0.0,0.0,0.0,0.0,30.84,15.71,22.13,25.36,36.79,49.43,0.00,0.0,0.00,0.0,0.0,0.0,56.21,52.51,71.56,0.00,0.00,0.00,0.00,12.46,0.00,0.0,0.0,0.0,0.00,12.46,0.00,0.00,0.0,0.0,0.0,4.31,0.26,0.0,0.0,0.0,56.21,69.29,71.83,0.76,0.61,9.88,19.63,61.64,22.88,0.16,0.00,0.23,20.56,62.26,32.99,0.00,0.00,0.00,1.8,0.00,0.95,0.0,0.79,0.0,1.80,0.79,0.95,22.96,63.23,34.06,0.00,0.0,0.11,0.0,0.0,0.0,0.6,0.16,0.0,7,7,10,60,80,90,10,30,20,2014-06-25,2014-07-31,2014-08-29,0,0,10,NaT,NaT,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,0.0,0.0,0.0,60.0,80.0,90.0,400.0,0,0.7

Let's build bins for the age of network column, which will indicate the number of years a client has been utilizing the T network.

In [45]:
age_range = [ 0,  2,  4,  6,  8, 10, 12]
age_bin = [ 1, 2, 3, 4, 5, 6]
df['age_group'] = pd.cut(df['aon_yr'], age_range, labels=age_bin)
df['age_group'] = df['age_group'].astype(str)
df['age_group'].head()

0    2
1    2
2    2
3    4
4    3
Name: age_group, dtype: object

In [46]:
# let us update our categorical column list
cat_cols.append('age_group')
cat_cols

['night_pck_user_6',
 'night_pck_user_7',
 'night_pck_user_8',
 'fb_user_6',
 'fb_user_7',
 'fb_user_8',
 'age_group']

# 6 Handling Missing values

## 6.1 Checking the null values

In [47]:
null = round(100*(df.isnull().sum()/len(df.index)),2).sort_values(ascending = False)
null = null[null!=0]
null

arpu_2g_6                   74.85
fb_user_6                   74.85
arpu_3g_6                   74.85
date_of_last_rech_data_6    74.85
night_pck_user_6            74.85
total_rech_data_6           74.85
max_rech_data_6             74.85
count_rech_2g_6             74.85
av_rech_amt_data_6          74.85
count_rech_3g_6             74.85
arpu_2g_7                   74.43
count_rech_3g_7             74.43
fb_user_7                   74.43
date_of_last_rech_data_7    74.43
max_rech_data_7             74.43
count_rech_2g_7             74.43
total_rech_data_7           74.43
arpu_3g_7                   74.43
av_rech_amt_data_7          74.43
night_pck_user_7            74.43
count_rech_3g_8             73.66
night_pck_user_8            73.66
arpu_2g_8                   73.66
fb_user_8                   73.66
date_of_last_rech_data_8    73.66
total_rech_data_8           73.66
arpu_3g_8                   73.66
av_rech_amt_data_8          73.66
max_rech_data_8             73.66
count_rech_2g_8             73.66
loc_og_t2c_mou_8             5.38
loc_ic_mou_8                 5.38
loc_ic_t2m_mou_8             5.38
roam_og_mou_8                5.38
std_ic_t2t_mou_8             5.38
loc_ic_t2t_mou_8             5.38
std_ic_t2m_mou_8             5.38
std_ic_t2f_mou_8             5.38
og_others_8                  5.38
std_ic_mou_8                 5.38
spl_ic_mou_8                 5.38
spl_og_mou_8                 5.38
isd_ic_mou_8                 5.38
isd_og_mou_8                 5.38
std_og_t2m_mou_8             5.38
loc_og_t2f_mou_8             5.38
std_og_mou_8                 5.38
loc_og_mou_8                 5.38
loc_og_t2t_mou_8             5.38
std_og_t2f_mou_8             5.38
loc_og_t2m_mou_8             5.38
onnet_mou_8                  5.38
loc_ic_t2f_mou_8             5.38
ic_others_8                  5.38
offnet_mou_8                 5.38
roam_ic_mou_8                5.38
std_og_t2t_mou_8             5.38
ic_others_6                  3.94
std_ic_t2m_mou_6             3.94
std_ic_t2f_mou_6             3.94
std_ic_mou_6                 3.94
isd_ic_mou_6                 3.94
loc_ic_mou_6                 3.94
spl_ic_mou_6                 3.94
std_ic_t2t_mou_6             3.94
loc_og_t2t_mou_6             3.94
std_og_t2m_mou_6             3.94
std_og_mou_6                 3.94
isd_og_mou_6                 3.94
std_og_t2t_mou_6             3.94
spl_og_mou_6                 3.94
loc_og_mou_6                 3.94
og_others_6                  3.94
loc_og_t2c_mou_6             3.94
loc_og_t2f_mou_6             3.94
loc_og_t2m_mou_6             3.94
std_og_t2f_mou_6             3.94
loc_ic_t2m_mou_6             3.94
roam_og_mou_6                3.94
loc_ic_t2f_mou_6             3.94
onnet_mou_6                  3.94
roam_ic_mou_6                3.94
loc_ic_t2t_mou_6             3.94
offnet_mou_6                 3.94
roam_og_mou_7                3.86
std_og_t2m_mou_7             3.86
std_og_t2t_mou_7             3.86
onnet_mou_7                  3.86
offnet_mou_7                 3.86
loc_og_mou_7                 3.86
loc_og_t2t_mou_7             3.86
loc_og_t2c_mou_7             3.86
loc_og_t2f_mou_7             3.86
roam_ic_mou_7                3.86
loc_ic_mou_7                 3.86
loc_og_t2m_mou_7             3.86
loc_ic_t2f_mou_7             3.86
std_og_mou_7                 3.86
std_ic_t2m_mou_7             3.86
std_ic_mou_7                 3.86
og_others_7                  3.86
spl_ic_mou_7                 3.86
spl_og_mou_7                 3.86
isd_ic_mou_7                 3.86
isd_og_mou_7                 3.86
ic_others_7                  3.86
std_og_t2f_mou_7             3.86
std_ic_t2f_mou_7             3.86
loc_ic_t2t_mou_7             3.86
std_ic_t2t_mou_7             3.86
loc_ic_t2m_mou_7             3.86
date_of_last_rech_8          3.62
date_of_last_rech_7          1.77
date_of_last_rech_6          1.61
dtype: float64

`Observation`: After analysing I have got the 74.85% missing values for some features in this dataset.

## 6.2 Imputation of missing values

In [49]:
#Observe missing values in recharge columns 
rech_col = [i for i in df.columns if 'rech' in i]
rech_6_col = [i for i in rech_col if '6' in i]
rech_7_col = [i for i in rech_col if '7' in i]
rech_8_col = [i for i in rech_col if '8' in i]

In [51]:
#Observe missing values in recharge columns in the month of june(6)
rech_6 = pd.DataFrame(df[rech_6_col])

#adding some other columns describing data usage of customer in june(6)
vol_col = df[["vol_2g_mb_6",'vol_3g_mb_6']]

rech_6 = pd.concat([rech_6,vol_col], axis = 1) 
rech_6.sample(2)

,total_rech_num_6,total_rech_amt_6,max_rech_amt_6,date_of_last_rech_6,date_of_last_rech_data_6,total_rech_data_6,max_rech_data_6,count_rech_2g_6,count_rech_3g_6,av_rech_amt_data_6,vol_2g_mb_6,vol_3g_mb_6
46369,9,110,110,2014-06-27,2014-06-24,2.0,98.0,2.0,0.0,196.0,0.53,604.31
78475,4,100,100,2014-06-27,NaT,NaN,NaN,NaN,NaN,NaN,0.00,0.00

`Observation`: The missing values for max rech, count rech 2g, and 3g are displayed in the table above whenever the date of the last recharge is absent. As observed in the preceding table, the mobile internet use (2G and 3G data) for these values is zero. As there were no client recharges, I would thus impute these missing values with a value of zero.

In [52]:
#Similarly, observe missing values in recharge columns for the month of july(7)
rech_7_col

['total_rech_num_7',
 'total_rech_amt_7',
 'max_rech_amt_7',
 'date_of_last_rech_7',
 'date_of_last_rech_data_7',
 'total_rech_data_7',
 'max_rech_data_7',
 'count_rech_2g_7',
 'count_rech_3g_7',
 'av_rech_amt_data_7']

In [53]:
rech_7 = pd.DataFrame(df[rech_7_col])

#adding some other columns describing data usage of customer in july
vol_col = df[["vol_2g_mb_7",'vol_3g_mb_7']]

rech_7 = pd.concat([rech_7,vol_col], axis = 1) 
rech_7.sample(2)

,total_rech_num_7,total_rech_amt_7,max_rech_amt_7,date_of_last_rech_7,date_of_last_rech_data_7,total_rech_data_7,max_rech_data_7,count_rech_2g_7,count_rech_3g_7,av_rech_amt_data_7,vol_2g_mb_7,vol_3g_mb_7
68716,12,776,110,2014-07-28,NaT,NaN,NaN,NaN,NaN,NaN,0.0,0.0
83408,3,240,120,2014-07-27,NaT,NaN,NaN,NaN,NaN,NaN,0.0,0.0

`Observation`: When the date of the previous recharge is absent, the associated values for max rech, count rech 2g, and 3g are also missing, as shown in the table above. According to the preceding table, the mobile internet consumption (2G and 3G data) corresponding to these numbers is zero. Therefore, I will replace these missing numbers with zero, as the consumer did not do any recharges. This resembles the trend observed throughout the month of June.

In [54]:
#Similarly,observe missing values in recharge columns in the month of August(8)
rech_8_col

['total_rech_num_8',
 'total_rech_amt_8',
 'max_rech_amt_8',
 'date_of_last_rech_8',
 'date_of_last_rech_data_8',
 'total_rech_data_8',
 'max_rech_data_8',
 'count_rech_2g_8',
 'count_rech_3g_8',
 'av_rech_amt_data_8']

In [55]:
rech_8 = pd.DataFrame(df[rech_8_col])

# adding some other columns describing data usage of customer in August
vol_col = df[["vol_2g_mb_8",'vol_3g_mb_8']]

rech_8 = pd.concat([rech_8,vol_col], axis = 1) 
rech_8.sample(2)

,total_rech_num_8,total_rech_amt_8,max_rech_amt_8,date_of_last_rech_8,date_of_last_rech_data_8,total_rech_data_8,max_rech_data_8,count_rech_2g_8,count_rech_3g_8,av_rech_amt_data_8,vol_2g_mb_8,vol_3g_mb_8
36712,28,777,50,2014-08-31,NaT,NaN,NaN,NaN,NaN,NaN,0.0,0.0
27308,16,376,50,2014-08-30,NaT,NaN,NaN,NaN,NaN,NaN,0.0,0.0

`Observation`: Similar to the months of June and July, the values for max rech, count rech 2g, and 3g are missing if the date of the last recharge is absent. According to the preceding table, the mobile internet consumption (2G and 3G data) corresponding to these numbers is zero. Therefore, let's impute these missing numbers with zero, given that there were no client recharges. This is identical to the trend observed throughout the months of June and July.

## 6.3 Filling the missing value by zero: Numerical features

In [57]:
# Let's use zero for the missing recharge column data.

impute_0 = [ 'date_of_last_rech_data_6','max_rech_data_6','count_rech_2g_6','count_rech_3g_6',
           'date_of_last_rech_data_7','max_rech_data_7','count_rech_2g_7','count_rech_3g_7',
           'date_of_last_rech_data_8','max_rech_data_8','count_rech_2g_8','count_rech_3g_8']

df[impute_0] = df[impute_0].apply(lambda x: x.fillna(0))

In [58]:
# Now Checking Null values
null = round(100*(df.isnull().sum()/len(df.index)),2).sort_values(ascending = False)
null = null[null!=0]
null

fb_user_6              74.85
arpu_2g_6              74.85
total_rech_data_6      74.85
av_rech_amt_data_6     74.85
arpu_3g_6              74.85
night_pck_user_6       74.85
fb_user_7              74.43
total_rech_data_7      74.43
arpu_2g_7              74.43
night_pck_user_7       74.43
arpu_3g_7              74.43
av_rech_amt_data_7     74.43
arpu_3g_8              73.66
arpu_2g_8              73.66
night_pck_user_8       73.66
fb_user_8              73.66
total_rech_data_8      73.66
av_rech_amt_data_8     73.66
std_og_t2m_mou_8        5.38
std_og_mou_8            5.38
std_og_t2f_mou_8        5.38
std_ic_t2m_mou_8        5.38
std_ic_mou_8            5.38
std_ic_t2f_mou_8        5.38
loc_ic_t2f_mou_8        5.38
std_ic_t2t_mou_8        5.38
isd_og_mou_8            5.38
std_og_t2t_mou_8        5.38
loc_ic_mou_8            5.38
spl_og_mou_8            5.38
og_others_8             5.38
loc_ic_t2m_mou_8        5.38
spl_ic_mou_8            5.38
loc_og_t2c_mou_8        5.38
loc_og_t2m_mou_8        5.38
loc_og_t2f_mou_8        5.38
onnet_mou_8             5.38
offnet_mou_8            5.38
roam_ic_mou_8           5.38
roam_og_mou_8           5.38
loc_og_t2t_mou_8        5.38
isd_ic_mou_8            5.38
loc_ic_t2t_mou_8        5.38
ic_others_8             5.38
loc_og_mou_8            5.38
std_ic_t2m_mou_6        3.94
loc_ic_t2t_mou_6        3.94
std_ic_t2f_mou_6        3.94
std_ic_t2t_mou_6        3.94
ic_others_6             3.94
loc_ic_mou_6            3.94
loc_ic_t2f_mou_6        3.94
std_ic_mou_6            3.94
loc_ic_t2m_mou_6        3.94
isd_ic_mou_6            3.94
spl_ic_mou_6            3.94
isd_og_mou_6            3.94
std_og_t2f_mou_6        3.94
std_og_mou_6            3.94
loc_og_t2c_mou_6        3.94
loc_og_t2m_mou_6        3.94
std_og_t2m_mou_6        3.94
loc_og_mou_6            3.94
loc_og_t2t_mou_6        3.94
spl_og_mou_6            3.94
roam_og_mou_6           3.94
og_others_6             3.94
roam_ic_mou_6           3.94
std_og_t2t_mou_6        3.94
offnet_mou_6            3.94
onnet_mou_6             3.94
loc_og_t2f_mou_6        3.94
ic_others_7             3.86
loc_og_mou_7            3.86
isd_ic_mou_7            3.86
loc_ic_t2t_mou_7        3.86
loc_og_t2f_mou_7        3.86
loc_og_t2m_mou_7        3.86
loc_og_t2t_mou_7        3.86
roam_og_mou_7           3.86
roam_ic_mou_7           3.86
offnet_mou_7            3.86
onnet_mou_7             3.86
std_og_t2t_mou_7        3.86
loc_og_t2c_mou_7        3.86
spl_ic_mou_7            3.86
loc_ic_t2m_mou_7        3.86
std_ic_t2m_mou_7        3.86
isd_og_mou_7            3.86
std_ic_t2t_mou_7        3.86
spl_og_mou_7            3.86
loc_ic_mou_7            3.86
loc_ic_t2f_mou_7        3.86
std_ic_t2f_mou_7        3.86
og_others_7             3.86
std_og_t2f_mou_7        3.86
std_ic_mou_7            3.86
std_og_t2m_mou_7        3.86
std_og_mou_7            3.86
date_of_last_rech_8     3.62
date_of_last_rech_7     1.77
date_of_last_rech_6     1.61
dtype: float64

## 6.4 Imputing Categorical columns

In [59]:
#Impute the missing values in categorical columns by (-1). 
df[cat_cols] = df[cat_cols].apply(lambda x: x.fillna(-1)) 
df[cat_cols] = df[cat_cols].astype('str')
df[cat_cols].sample(2)

,night_pck_user_6,night_pck_user_7,night_pck_user_8,fb_user_6,fb_user_7,fb_user_8,age_group
76580,-1.0,-1.0,0.0,-1.0,-1.0,0.0,1
55282,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,5

In [60]:
# Now Checking Null values
null = round(100*(high_val.isnull().sum()/len(high_val.index)),2).sort_values(ascending = False)
null = null[null!=0]
null

arpu_2g_6                   64.05
date_of_last_rech_data_6    64.05
count_rech_3g_6             64.05
count_rech_2g_6             64.05
max_rech_data_6             64.05
night_pck_user_6            64.05
total_rech_data_6           64.05
arpu_3g_6                   64.05
fb_user_6                   64.05
av_rech_amt_data_6          64.05
date_of_last_rech_data_7    62.29
av_rech_amt_data_7          62.29
max_rech_data_7             62.29
fb_user_7                   62.29
count_rech_2g_7             62.29
arpu_2g_7                   62.29
count_rech_3g_7             62.29
total_rech_data_7           62.29
night_pck_user_7            62.29
arpu_3g_7                   62.29
arpu_3g_8                   59.43
fb_user_8                   59.43
count_rech_3g_8             59.43
av_rech_amt_data_8          59.43
count_rech_2g_8             59.43
arpu_2g_8                   59.43
date_of_last_rech_data_8    59.43
max_rech_data_8             59.43
total_rech_data_8           59.43
night_pck_user_8            59.43
fb_user_9                   59.25
count_rech_3g_9             59.25
arpu_2g_9                   59.25
date_of_last_rech_data_9    59.25
total_rech_data_9           59.25
night_pck_user_9            59.25
av_rech_amt_data_9          59.25
max_rech_data_9             59.25
arpu_3g_9                   59.25
count_rech_2g_9             59.25
spl_ic_mou_9                 2.69
loc_ic_t2m_mou_9             2.69
std_ic_mou_9                 2.69
loc_ic_t2f_mou_9             2.69
loc_ic_mou_9                 2.69
isd_og_mou_9                 2.69
std_ic_t2t_mou_9             2.69
std_ic_t2f_mou_9             2.69
spl_og_mou_9                 2.69
std_ic_t2m_mou_9             2.69
og_others_9                  2.69
std_og_mou_9                 2.69
roam_ic_mou_9                2.69
onnet_mou_9                  2.69
offnet_mou_9                 2.69
roam_og_mou_9                2.69
isd_ic_mou_9                 2.69
ic_others_9                  2.69
std_og_t2m_mou_9             2.69
std_og_t2t_mou_9             2.69
loc_og_t2t_mou_9             2.69
loc_og_mou_9                 2.69
std_og_t2f_mou_9             2.69
loc_ic_t2t_mou_9             2.69
loc_og_t2m_mou_9             2.69
loc_og_t2c_mou_9             2.69
loc_og_t2f_mou_9             2.69
loc_ic_t2f_mou_6             1.98
loc_ic_mou_6                 1.98
isd_ic_mou_6                 1.98
std_ic_t2m_mou_6             1.98
std_ic_t2f_mou_6             1.98
std_ic_mou_6                 1.98
ic_others_6                  1.98
spl_ic_mou_6                 1.98
loc_ic_t2m_mou_6             1.98
std_ic_t2t_mou_6             1.98
loc_og_t2m_mou_6             1.98
onnet_mou_6                  1.98
std_og_mou_6                 1.98
std_og_t2f_mou_6             1.98
spl_og_mou_6                 1.98
offnet_mou_6                 1.98
roam_ic_mou_6                1.98
og_others_6                  1.98
roam_og_mou_6                1.98
loc_og_t2t_mou_6             1.98
std_og_t2m_mou_6             1.98
isd_og_mou_6                 1.98
loc_ic_t2t_mou_6             1.98
loc_og_mou_6                 1.98
loc_og_t2c_mou_6             1.98
loc_og_t2f_mou_6             1.98
std_og_t2t_mou_6             1.98
date_of_last_rech_9          1.31
loc_og_t2m_mou_8             1.29
isd_ic_mou_8                 1.29
std_og_t2f_mou_8             1.29
loc_og_t2t_mou_8             1.29
ic_others_8                  1.29
std_og_t2t_mou_8             1.29
std_og_t2m_mou_8             1.29
offnet_mou_8                 1.29
loc_og_t2c_mou_8             1.29
roam_ic_mou_8                1.29
spl_ic_mou_8                 1.29
roam_og_mou_8                1.29
loc_og_mou_8                 1.29
loc_og_t2f_mou_8             1.29
loc_ic_t2t_mou_8             1.29
spl_og_mou_8                 1.29
std_og_mou_8                 1.29
loc_ic_t2m_mou_8             1.29
og_others_8                  1.29
onnet_mou_8                  1.29
std_ic_t2m_mou_8             1.29
isd_og_mou_8                 1.29
std_ic_t2t_mou_8             1.29
std_ic_mou_8                 1.29
loc_ic_t2f_mou_8             1.29
std_ic_t2f_mou_8             1.29
loc_ic_mou_8                 1.29
spl_ic_mou_7                 1.04
loc_og_t2t_mou_7             1.04
std_ic_t2t_mou_7             1.04
std_og_t2t_mou_7             1.04
loc_og_mou_7                 1.04
loc_ic_mou_7                 1.04
og_others_7                  1.04
loc_og_t2c_mou_7             1.04
loc_ic_t2f_mou_7             1.04
loc_og_t2f_mou_7             1.04
loc_ic_t2t_mou_7             1.04
loc_og_t2m_mou_7             1.04
roam_og_mou_7                1.04
std_og_t2f_mou_7             1.04
std_og_t2m_mou_7             1.04
spl_og_mou_7                 1.04
std_ic_t2m_mou_7             1.04
roam_ic_mou_7                1.04
std_og_mou_7                 1.04
isd_og_mou_7                 1.04
isd_ic_mou_7                 1.04
loc_ic_t2m_mou_7             1.04
std_ic_t2f_mou_7             1.04
offnet_mou_7                 1.04
onnet_mou_7                  1.04
ic_others_7                  1.04
std_ic_mou_7                 1.04
date_of_last_rech_8          0.85
date_of_last_rech_6          0.59
date_of_last_rech_7          0.36
dtype: float64

## 6.5 Dropping columns with more than 40% missing values

More than forty percent of the average revenue per user during both the good and action phases are missing. Since the focus of this research is the identification of consumers who are likely to churn based only on usage-based churn, I may safely exclude these columns without compromising the research.

In [62]:
miss = round(100*(df.isnull().sum()/len(df.index)),2).sort_values(ascending = False) 

miss = pd.DataFrame(miss[miss >= 40])
threshold_col = miss.index

df = df.drop(threshold_col,1)

In [63]:
df.shape

(99999, 152)

## 6.6 Dropping missing values for out going calls for month of June, July, and August

#### For Month of June

In [66]:
#According to my business domain knowledge, the total_og column represents the sum of local, standard, special, and other outgoing calls.
og_call_6 = ['loc_og_mou_6','std_og_mou_6','isd_og_mou_6','spl_og_mou_6','og_others_6','total_og_mou_6']
total_og_6 = df[og_call_6]

#limiting the filtering to clients who have made no outbound calls.
total_og_6.loc[total_og_6['total_og_mou_6']==0].sample(2)

,loc_og_mou_6,std_og_mou_6,isd_og_mou_6,spl_og_mou_6,og_others_6,total_og_mou_6
26815,0.0,0.0,0.0,0.0,0.0,0.0
37108,NaN,NaN,NaN,NaN,NaN,0.0

`Observation`: Based on my understanding of the business area and the preceding table, I can deduce that when the total number of outgoing calls for a given month is 0, no outgoing calls have been made. I am going to change the missing values for local outgoing calls, normal outgoing calls, special outgoing calls, and other outgoing calls with 0.

In [67]:
#Let's see whether our assumption is correct or not: the sum of all outgoing calls equals the 'total_og_mou_6'.

df['outgoing_total_6'] = df['loc_og_mou_6']+ df['std_og_mou_6']+df['isd_og_mou_6']+df['spl_og_mou_6']+df['og_others_6']
df[['outgoing_total_6','total_og_mou_6']].dropna().corr()

                  outgoing_total_6  total_og_mou_6
outgoing_total_6               1.0             1.0
total_og_mou_6                 1.0             1.0

`Observation`: From the above table, it is evident that these variables are associated; thus, when the total number of outgoing calls for a given month is 0,that means no outbound calls have been made. as a result, I am going to replace the missing values for 'local outgoing calls', 'normal outgoing calls', 'special outgoing calls', and 'other outgoing calls' with 0.

In [69]:
#Imputing by '0'

df[og_call_6] = df[og_call_6].fillna(0)

### local outgoing calls(T2T,T2M,T2F & T2C)

In [70]:
og_loc_6 = ['loc_og_t2t_mou_6','loc_og_t2m_mou_6','loc_og_t2f_mou_6','loc_og_t2c_mou_6','loc_og_mou_6']
loc_og_6 = df[og_loc_6]

# filtering only those clients who didn't make any 'local outgoing calls'
loc_og_6.loc[loc_og_6 ['loc_og_mou_6']==0].sample(2)

,loc_og_t2t_mou_6,loc_og_t2m_mou_6,loc_og_t2f_mou_6,loc_og_t2c_mou_6,loc_og_mou_6
78032,0.0,0.0,0.0,0.0,0.0
9041,0.0,0.0,0.0,0.0,0.0

Local outbound calls in any given month are equal to the total of all local outgoing call kinds, i.e. (T2T,T2M,T2F & T2C)

The monthly total number of local outbound calls (T2T,T2M,T2F, and T2C) is zero. Now, I will replace the missing value with zero.

In [71]:
#Lets verify is the assumption right or not, sum of 'all local outgoing calls' is 
#equal to the the 'total local outgoing call'
#"loc_og_mou_6"

df['loc_outgoing_total_6'] = df['loc_og_t2t_mou_6']+ df['loc_og_t2m_mou_6']+df['loc_og_t2f_mou_6']+df['loc_og_t2c_mou_6']
df[['loc_outgoing_total_6','loc_og_mou_6']].dropna().corr().round()

                      loc_outgoing_total_6  loc_og_mou_6
loc_outgoing_total_6                   1.0           1.0
loc_og_mou_6                           1.0           1.0

`Observation:` From the above table, it is evident that these variables are associated; thus, when the total number of local outgoing calls for a given month is 0,that means no local outbound calls have been made. as a result, I am going to replace the missing values for T2T,T2M,T2F & T2C by zero

In [72]:
# Imputing by '0'
df[og_loc_6] = df[og_loc_6].fillna(0)

#### total standard outgoing calls

In [74]:
og_std_6 = ['std_og_t2t_mou_6','std_og_t2m_mou_6','std_og_t2f_mou_6','std_og_mou_6']
std_og_6 = df[og_std_6]
std_og_6.sample(5)

       std_og_t2t_mou_6  std_og_t2m_mou_6  std_og_t2f_mou_6  std_og_mou_6
39992             14.93              0.46              0.00         15.39
49298            177.36             99.61              0.00        276.98
72895              0.00              0.00              0.66          0.66
68615             19.44             15.73             14.49         49.68
16297            217.08              5.49              0.00        222.58

In [75]:
# Imputing by '0'
df[og_std_6] = df[og_std_6].fillna(0)

#### For Month of July

Similar process is applied like June

#### Total Outgoing Call

In [77]:
# From the business domain knowledge, we know that total_og column is the addition of local , standard, special and other outgoing calls
og_call_7 = ['loc_og_mou_7','std_og_mou_7','isd_og_mou_7','spl_og_mou_7','og_others_7','total_og_mou_7']
total_og_7 = high_val[og_call_7]
# filtering only those clients who have made no outgoing calls
total_og_7.loc[total_og_7['total_og_mou_7']==0].sample(2)

,loc_og_mou_7,std_og_mou_7,isd_og_mou_7,spl_og_mou_7,og_others_7,total_og_mou_7
91223,NaN,NaN,NaN,NaN,NaN,0.0
58319,0.0,0.0,0.0,0.0,0.0,0.0

In [78]:
#Lets verify is our assumption right or not, sum of all outgoing calls is equal to the the tota_og_mou_7
df['outgoing_total_7'] = df['loc_og_mou_7']+ df['std_og_mou_7']+df['isd_og_mou_7']+df['spl_og_mou_7']+df['og_others_7']
df[['outgoing_total_7','total_og_mou_7']].dropna().corr()

                  outgoing_total_7  total_og_mou_7
outgoing_total_7               1.0             1.0
total_og_mou_7                 1.0             1.0

In [79]:
# Imputing by '0'
df[og_call_7] = df[og_call_7].fillna(0)

In [81]:
og_loc_7 = ['loc_og_t2t_mou_7','loc_og_t2m_mou_7','loc_og_t2f_mou_7','loc_og_t2c_mou_7','loc_og_mou_7']
loc_og_7 = high_val[og_loc_7]

# filtering only those clients who didn't made any local outgoing calls
loc_og_7.loc[loc_og_7 ['loc_og_mou_7']==0].sample(3)

,loc_og_t2t_mou_7,loc_og_t2m_mou_7,loc_og_t2f_mou_7,loc_og_t2c_mou_7,loc_og_mou_7
77218,0.0,0.0,0.0,0.00,0.0
93697,0.0,0.0,0.0,0.01,0.0
35221,0.0,0.0,0.0,0.00,0.0

#### T2T,T2M,T2F & T2C

In [82]:
#Lets verify is our assumption right or not, sum of all local outgoing calls is equal to 
#the total local outgoing call
#"loc_og_mou_7"

df['loc_outgoing_total_7'] = df['loc_og_t2t_mou_7']+ df['loc_og_t2m_mou_7']+df['loc_og_t2f_mou_7']+df['loc_og_t2c_mou_7']
df[['loc_outgoing_total_7','loc_og_mou_7']].dropna().corr().round()

                      loc_outgoing_total_7  loc_og_mou_7
loc_outgoing_total_7                   1.0           1.0
loc_og_mou_7                           1.0           1.0

In [83]:
# Imputing by '0'
df[og_loc_7] = df[og_loc_7].fillna(0)

In [84]:
og_std_7 = ['std_og_t2t_mou_7','std_og_t2m_mou_7','std_og_t2f_mou_7','std_og_mou_7']
std_og_7 = high_val[og_std_7]
std_og_7.sample(3)

       std_og_t2t_mou_7  std_og_t2m_mou_7  std_og_t2f_mou_7  std_og_mou_7
83968           1428.46             71.19              0.00       1499.66
89162             15.38             33.51             12.51         61.41
56651            541.61            229.96              0.00        771.58

#### Total standard outgoing calls

In [85]:
#Lets verify is our assumption right or not, sum of all std outgoing calls is equal to 
#the total std outgoing call
#"std_og_mou_7"

df['std_outgoing_total_7'] = df['std_og_t2t_mou_7']+ df['std_og_t2m_mou_7']+df['std_og_t2f_mou_7']
df[['std_outgoing_total_7','std_og_mou_7']].dropna().corr()

                      std_outgoing_total_7  std_og_mou_7
std_outgoing_total_7                   1.0           1.0
std_og_mou_7                           1.0           1.0

In [86]:
# Imputing by '0'
df[og_std_7] = df[og_std_7].fillna(0)

#### For Month of August

Similar process is applied like June

#### Total Outgoing Call

In [88]:
# From the business domain knowledge, we know that total_og column is the addition of local , standard, special and other outgoing calls
og_call_8 = ['loc_og_mou_8','std_og_mou_8','isd_og_mou_8','spl_og_mou_8','og_others_8','total_og_mou_8']
total_og_8 = high_val[og_call_8]
# filtering only those clients who have made no outgoing calls
total_og_8.loc[total_og_8['total_og_mou_8']==0].sample(3)

,loc_og_mou_8,std_og_mou_8,isd_og_mou_8,spl_og_mou_8,og_others_8,total_og_mou_8
24362,0.0,0.0,0.0,0.0,0.0,0.0
69272,0.0,0.0,0.0,0.0,0.0,0.0
80071,0.0,0.0,0.0,0.0,0.0,0.0

In [89]:
#Lets verify is our assumption right or not, sum of 
#all outgoing calls is equal to the tota_og_mou_8

df['outgoing_total_8'] = df['loc_og_mou_8']+ df['std_og_mou_8']+df['isd_og_mou_8']+df['spl_og_mou_8']+df['og_others_8']
df[['outgoing_total_8','total_og_mou_8']].dropna().corr()

                  outgoing_total_8  total_og_mou_8
outgoing_total_8               1.0             1.0
total_og_mou_8                 1.0             1.0

In [90]:
# Imputing by '0'
df[og_call_8] = df[og_call_8].fillna(0)

#### T2T,T2M,T2F & T2C

In [92]:
og_loc_8 = ['loc_og_t2t_mou_8','loc_og_t2m_mou_8','loc_og_t2f_mou_8','loc_og_t2c_mou_8','loc_og_mou_8']
loc_og_8 = high_val[og_loc_8]

# filtering only those clients who have made no local outgoing calls
loc_og_8.loc[loc_og_8 ['loc_og_mou_8']==0].sample(2)

,loc_og_t2t_mou_8,loc_og_t2m_mou_8,loc_og_t2f_mou_8,loc_og_t2c_mou_8,loc_og_mou_8
58810,0.0,0.0,0.0,4.01,0.0
85655,0.0,0.0,0.0,0.00,0.0

In [93]:
#Lets verify is our assumption right or not, sum of all local outgoing calls is equal to the the total local outgoing call
#"loc_og_mou_8"

df['loc_outgoing_total_8'] = df['loc_og_t2t_mou_8']+ df['loc_og_t2m_mou_8']+df['loc_og_t2f_mou_8']+df['loc_og_t2c_mou_8']
df[['loc_outgoing_total_8','loc_og_mou_8']].dropna().corr().round()

                      loc_outgoing_total_8  loc_og_mou_8
loc_outgoing_total_8                   1.0           1.0
loc_og_mou_8                           1.0           1.0

In [94]:
# Imputing by '0'
df[og_loc_8] = df[og_loc_8].fillna(0)

#### std outgoing calls

In [96]:
og_std_8 = ['std_og_t2t_mou_8','std_og_t2m_mou_8','std_og_t2f_mou_8','std_og_mou_8']
std_og_8 = df[og_std_8]
std_og_8.sample(3)

       std_og_t2t_mou_8  std_og_t2m_mou_8  std_og_t2f_mou_8  std_og_mou_8
68119              0.00              0.00               0.0          0.00
55018              1.08             36.39               0.0         37.48
79577              0.00              0.00               0.0          0.00

In [97]:
#Lets verify is our assumption right or not, sum of all std outgoing 
#calls is equal to the total std outgoing call
#"std_og_mou_8"

df['std_outgoing_total_8'] = df['std_og_t2t_mou_8']+ df['std_og_t2m_mou_8']+df['std_og_t2f_mou_8']
df[['std_outgoing_total_8','std_og_mou_8']].dropna().corr()

                      std_outgoing_total_8  std_og_mou_8
std_outgoing_total_8                   1.0           1.0
std_og_mou_8                           1.0           1.0

In [98]:
# Imputing by '0'
high_val[og_std_8] = high_val[og_std_8].fillna(0)

## 6.7 Dropping missing values for incoming calls for month of June, July, and August

usage for local, standard, special and others¶

#### For month of June

In [99]:
# From the business domain knowledge, we know that total_ic column is the addition of local , standard, special andd other incoming calls
ic_call_6 = ['loc_ic_mou_6','std_ic_mou_6','isd_ic_mou_6','spl_ic_mou_6','ic_others_6','total_ic_mou_6']
total_ic_6 = df[ic_call_6]
# filtering only those clients who have made no outgoing calls
total_ic_6 .loc[total_ic_6 ['total_ic_mou_6']==0].sample(2)

,loc_ic_mou_6,std_ic_mou_6,isd_ic_mou_6,spl_ic_mou_6,ic_others_6,total_ic_mou_6
14986,NaN,NaN,NaN,NaN,NaN,0.0
92807,0.0,0.0,0.0,0.0,0.0,0.0

`Observation`: Based on my understanding of the business domain and the aforementioned statistics, I can deduce that when the total number of incoming calls is zero, no incoming calls are received during that month. The missing values can be replaced with 0 in the columns for local incoming calls, regular incoming calls, special incoming calls, and other incoming calls.

In [100]:
#Lets verify is our assumption right or not, sum of all incoming calls is equal to the tota_ic_mou_6

df['incoming_total_6'] = df['loc_ic_mou_6']+ df['std_ic_mou_6']+df['isd_ic_mou_6']+df['spl_ic_mou_6']+df['ic_others_6']
df[['incoming_total_6','total_ic_mou_6']].dropna().corr()

                  incoming_total_6  total_ic_mou_6
incoming_total_6               1.0             1.0
total_ic_mou_6                 1.0             1.0

`Observation`: As can be seen in the table above, when the total number of incoming calls is 0, no outgoing calls have been made during that month. 0 can be substituted for missing values in the columns for local outgoing calls, normal outgoing calls, special incoming calls, and other outgoing calls.

In [101]:
# Imputing by '0'
df[ic_call_6] = df[ic_call_6].fillna(0)

#### T2T,T2M,T2F & T2C

In [103]:
ic_loc_6 = ['loc_ic_t2t_mou_6','loc_ic_t2m_mou_6','loc_ic_t2f_mou_6','loc_ic_mou_6']
loc_ic_6= high_val[ic_loc_6]

# filtering only those clients who have made no local outgoing calls
loc_ic_6.loc[loc_ic_6['loc_ic_mou_6']==0].sample(3)

       loc_ic_t2t_mou_6  loc_ic_t2m_mou_6  loc_ic_t2f_mou_6  loc_ic_mou_6
90772               0.0               0.0               0.0           0.0
91056               0.0               0.0               0.0           0.0
99875               0.0               0.0               0.0           0.0

`Observation`:If the total number of local calls received in a particular month is zero, no local calls were received, i.e. T2T, T2M, T2F, and T2C. I am able to replace '0' for the missing equivalent numbers.

In [104]:
#Lets verify is our assumption right or not, sum of all local outgoing calls is equal to the 
#total local outgoing call
#"loc_ic_mou_6"

df['loc_incoming_total_6'] = df['loc_ic_t2t_mou_6']+ df['loc_ic_t2m_mou_6']+df['loc_ic_t2f_mou_6']
df[['loc_incoming_total_6','loc_ic_mou_6']].dropna().corr()

                      loc_incoming_total_6  loc_ic_mou_6
loc_incoming_total_6                   1.0           1.0
loc_ic_mou_6                           1.0           1.0

In [105]:
# Imputing by '0'
df[ic_loc_6] = df[ic_loc_6].fillna(0)

#### std incoming calls

It is obvious from the statistics that standard incoming calls in any given month equal the total of all standard incoming call categories, i.e. (T2T,T2M,T2F & T2C)

In [107]:
ic_std_6 = ['std_ic_t2t_mou_6','std_ic_t2m_mou_6','std_ic_t2f_mou_6','std_ic_mou_6']
std_ic_6 = df[ic_std_6]
std_ic_6.sample(3)

       std_ic_t2t_mou_6  std_ic_t2m_mou_6  std_ic_t2f_mou_6  std_ic_mou_6
32871               0.0              0.00              0.58          0.58
82174               0.0              8.11              0.00          8.11
67676               0.0              0.00              1.85          1.85

`Observation`:If the total number of regular outbound calls in a particular month is zero, no T2T, T2M, T2F, or T2C calls were made. I am able to substitute '0' for the missing values that correspond to them.

In [108]:
#Lets verify is our assumption right or not, sum of all std outgoing calls is equal to the total std outgoing call
#"std_ic_mou_6"

df['std_incoming_total_6'] = df['std_ic_t2t_mou_6']+ df['std_ic_t2m_mou_6']+df['std_ic_t2f_mou_6']
df[['std_incoming_total_6','std_ic_mou_6']].dropna().corr()

                      std_incoming_total_6  std_ic_mou_6
std_incoming_total_6                   1.0           1.0
std_ic_mou_6                           1.0           1.0

`Observation`:If the total number of standard outbound calls in a particular month is 0, then no standard calls, i.e. T2T, T2M, T2F, and T2C, were made.

In [109]:
# Imputing by '0'
df[ic_std_6] = df[ic_std_6].fillna(0)

#### For month of July

# Total Calls

In [111]:
# From the business domain knowledge, we know that total_ic column is the addition of local , standard, special andd other incoming calls
ic_call_7 = ['loc_ic_mou_7','std_ic_mou_7','isd_ic_mou_7','spl_ic_mou_7','ic_others_7','total_ic_mou_7']
total_ic_7 = high_val[ic_call_7]
# filtering only those clients who have made no outgoing calls
total_ic_7 .loc[total_ic_7 ['total_ic_mou_7']==0].sample(2)

,loc_ic_mou_7,std_ic_mou_7,isd_ic_mou_7,spl_ic_mou_7,ic_others_7,total_ic_mou_7
4916,0.0,0.0,0.0,0.0,0.0,0.0
54195,0.0,0.0,0.0,0.0,0.0,0.0

In [112]:
#Lets verify is our assumption right or not, sum of all local incoming calls is equal to the the total local incoming call
#"loc_ic_mou_7"

df['loc_incoming_total_7'] = df['loc_ic_mou_7']+ df['std_ic_mou_7']+df['isd_ic_mou_7']+df['spl_ic_mou_7']+df['ic_others_7']
df[['loc_incoming_total_7','total_ic_mou_7']].dropna().corr()

                      loc_incoming_total_7  total_ic_mou_7
loc_incoming_total_7                   1.0             1.0
total_ic_mou_7                         1.0             1.0

In [113]:
# Imputing by '0'
high_val[ic_call_7] = high_val[ic_call_7].fillna(0)

#### T2T,T2M,T2F & T2C

In [115]:
ic_loc_7 = ['loc_ic_t2t_mou_7','loc_ic_t2m_mou_7','loc_ic_t2f_mou_7','loc_ic_mou_7']
loc_ic_7= df[ic_loc_7]

# filtering only those clients who have made no local outgoing calls
loc_ic_7.loc[loc_ic_7['loc_ic_mou_7']==0].sample(3)

       loc_ic_t2t_mou_7  loc_ic_t2m_mou_7  loc_ic_t2f_mou_7  loc_ic_mou_7
86206               0.0               0.0               0.0           0.0
49820               0.0               0.0               0.0           0.0
15333               0.0               0.0               0.0           0.0

In [116]:
#Lets verify is our assumption right or not, sum of all local incoming calls is equal to the 
#total local incoming call
#"loc_ic_mou_7"

df['loc_incoming_total_7'] = df['loc_ic_t2t_mou_7']+ df['loc_ic_t2m_mou_7']+df['loc_ic_t2f_mou_7']
df[['loc_incoming_total_7','loc_ic_mou_7']].dropna().corr()

                      loc_incoming_total_7  loc_ic_mou_7
loc_incoming_total_7                   1.0           1.0
loc_ic_mou_7                           1.0           1.0

In [117]:
# Imputing by '0'
high_val[ic_loc_7] = high_val[ic_loc_7].fillna(0)

#### Standard Outgoing calls

In [119]:
ic_std_7 = ['std_ic_t2t_mou_7','std_ic_t2m_mou_7','std_ic_t2f_mou_7','std_ic_mou_7']
std_ic_7 = df[ic_std_7]
std_ic_7.sample(2)

       std_ic_t2t_mou_7  std_ic_t2m_mou_7  std_ic_t2f_mou_7  std_ic_mou_7
95519               0.0               0.0               0.0           0.0
27967               0.0               0.6               0.0           0.6

In [120]:
#Lets verify is our assumption right or not, sum of all local incoming calls is equal to the the total local incoming call
#"std_ic_mou_7"

df['std_incoming_total_7'] = df['std_ic_t2t_mou_7']+ df['std_ic_t2m_mou_7']+df['std_ic_t2f_mou_7']
df[['std_incoming_total_7','std_ic_mou_7']].dropna().corr()

                      std_incoming_total_7  std_ic_mou_7
std_incoming_total_7                   1.0           1.0
std_ic_mou_7                           1.0           1.0

In [121]:
# Imputing by '0'
high_val[ic_std_7] = high_val[ic_std_7].fillna(0)

#### For August Month

In [123]:
# From the business domain knowledge, we know that total_ic column is the addition of local , standard, special andd other incoming calls
ic_call_8 = ['loc_ic_mou_8','std_ic_mou_8','isd_ic_mou_8','spl_ic_mou_8','ic_others_8','total_ic_mou_8']
total_ic_8 = df[ic_call_8]
# filtering only those clients who have made no outgoing calls
total_ic_8 .loc[total_ic_8['total_ic_mou_8']==0].sample(3)

,loc_ic_mou_8,std_ic_mou_8,isd_ic_mou_8,spl_ic_mou_8,ic_others_8,total_ic_mou_8
4814,0.0,0.0,0.0,0.0,0.0,0.0
51257,NaN,NaN,NaN,NaN,NaN,0.0
81760,0.0,0.0,0.0,0.0,0.0,0.0

In [124]:
#Lets verify is our assumption right or not, sum of all incoming calls is equal to the the tota_ic_mou_8

df['incoming_total_8'] = df['loc_ic_mou_8']+ df['std_ic_mou_8']+df['isd_ic_mou_8']+df['spl_ic_mou_8']+df['ic_others_8']
df[['incoming_total_8','total_ic_mou_8']].dropna().corr()

                  incoming_total_8  total_ic_mou_8
incoming_total_8               1.0             1.0
total_ic_mou_8                 1.0             1.0

In [125]:
# Imputing by '0'
high_val[ic_call_8] = high_val[ic_call_8].fillna(0)

In [127]:
ic_loc_8 = ['loc_ic_t2t_mou_8','loc_ic_t2m_mou_8','loc_ic_t2f_mou_8','loc_ic_mou_8']
loc_ic_8= df[ic_loc_8]

# filtering only those clients who have made no local outgoing calls
loc_ic_8.loc[loc_ic_8['loc_ic_mou_8']==0].sample(3)

       loc_ic_t2t_mou_8  loc_ic_t2m_mou_8  loc_ic_t2f_mou_8  loc_ic_mou_8
55959               0.0               0.0               0.0           0.0
89241               0.0               0.0               0.0           0.0
46235               0.0               0.0               0.0           0.0

In [128]:
#Lets verify is our assumption right or not, sum of all local incoming calls is equal to the the total local incoming call
#"loc_ic_mou_8"

df['loc_incoming_total_8'] = df['loc_ic_t2t_mou_8']+ df['loc_ic_t2m_mou_8']+df['loc_ic_t2f_mou_8']
df[['loc_incoming_total_8','loc_ic_mou_8']].dropna().corr()

                      loc_incoming_total_8  loc_ic_mou_8
loc_incoming_total_8                   1.0           1.0
loc_ic_mou_8                           1.0           1.0

In [129]:
# Imputing by '0'
high_val[ic_loc_8] = high_val[ic_loc_8].fillna(0)

In [131]:
ic_std_8 = ['std_ic_t2t_mou_8','std_ic_t2m_mou_8','std_ic_t2f_mou_8','std_ic_mou_8']
std_ic_8 = df[ic_std_8]
std_ic_8.sample(3)

       std_ic_t2t_mou_8  std_ic_t2m_mou_8  std_ic_t2f_mou_8  std_ic_mou_8
84878              1.00              0.00              0.00          1.00
59047              0.00              9.23              0.00          9.23
16165              0.71             88.06              7.01         95.79

In [132]:
#Lets verify is our assumption right or not, sum of all local incoming calls is equal to the the total local incoming call
#"std_ic_mou_8"

df['std_incoming_total_8'] = df['std_ic_t2t_mou_8']+ df['std_ic_t2m_mou_8']+df['std_ic_t2f_mou_8']
df[['std_incoming_total_8','std_ic_mou_8']].dropna().corr()

                      std_incoming_total_8  std_ic_mou_8
std_incoming_total_8                   1.0           1.0
std_ic_mou_8                           1.0           1.0

In [133]:
# Imputing by '0'
df[ic_std_8] = df[ic_std_8].fillna(0)

In [ ]:
## Let us now check the % of null values
null = round(100*(high_val.isnull().sum()/len(high_val.index)),2).sort_values(ascending = False)
null = null[null!=0]
null